### ISSUE TITLE
Sass breaks with Ruby 2.1.0 and Rails 3.2.x

### ISSUE THREAD

**Issue by spajus** [sass/sass#1057]
Didn't try it with newer Rails version, but that's what happens when Sass is being loaded:

``` ruby
-bash-4.1$ ruby -v
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux]
-bash-4.1$ rails c
/var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:1132:in `module_function': undefined method `singleton_class?' for module `Sass::Util' (NameError)
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:1132:in `block in <module:Util>'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:1132:in `each'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:1132:in `<module:Util>'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:14:in `<module:Sass>'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:12:in `<top (required)>'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/version.rb:2:in `<top (required)>'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `block in require'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/activesupport-3.2.16/lib/active_support/dependencies.rb:251:in `require'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass.rb:9:in `<top (required)>'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.0/lib/bundler/runtime.rb:76:in `require'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.0/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.0/lib/bundler/runtime.rb:72:in `each'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.0/lib/bundler/runtime.rb:72:in `block in require'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.0/lib/bundler/runtime.rb:61:in `each'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.0/lib/bundler/runtime.rb:61:in `require'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0@global/gems/bundler-1.5.0/lib/bundler.rb:131:in `require'
    from /var/lib/jenkins/jobs/core-ruby2.1/workspace/config/application.rb:17:in `<top (required)>'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/railties-3.2.16/lib/rails/commands.rb:39:in `require'
    from /var/lib/jenkins/.rvm/gems/ruby-2.1.0/gems/railties-3.2.16/lib/rails/commands.rb:39:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Tried it without Rails, works.

**Comment by cheald** [comment]
This is because ActiveSupport extends `singleton_class?` onto Class, which appears to remove it from the Module method list (likely due to Ruby 2.1's new method cache stuff). I've filed a bug report here: https://bugs.ruby-lang.org/issues/9311

I'm also going to file a bug report with the ActiveSupport project. In the meantime, Sass can fix this by changing:

```
(Sass::Util.methods - Module.methods).each {|method| module_function method}
```

to:

```
(Sass::Util.methods - Module.methods - Object.methods).each {|method| module_function method }
```

I'll submit a PR shortly.

**Comment by jsmestad** [comment]
Just for people searching. This also occurs in Rails 4.x as well.

**Comment by morenoh149** [comment]
I'm getting a similar error when trying to add the jasmine gem to my rails 4 project 

```
rails g jasmine:install
/Users/harrymoreno/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:1132:in `module_function': undefined method `singleton_class?' for module `Sass::Util' (NameError)
    from /Users/harrymoreno/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:1132:in `block in <module:Util>'
    from /Users/harrymoreno/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:1132:in `each'
    from /Users/harrymoreno/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:1132:in `<module:Util>'
    from /Users/harrymoreno/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:14:in `<module:Sass>'
    from /Users/harrymoreno/.rvm/gems/ruby-2.1.0/gems/sass-3.3.0.rc.2/lib/sass/util.rb:12:in `<top (required)>'
    from /Users/harrymoreno/.rvm/gems/ruby-2.1.0/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
```

#### my Gemfile

```
source 'https://rubygems.org'
ruby '2.1.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
#gem 'sqlite3'
gem 'pg'
gem 'devise'
gem 'font-awesome-rails'
gem 'bootstrap-sass', '~> 3.0.3.0'
gem 'simple_form', git: 'https://github.com/plataformatec/simple_form.git'
gem 'carrierwave'
gem 'fog', '~> 1.3.1'
gem 'mini_magick'
gem 'rails_12factor'
gem 'friendly_id', '~> 5.0.0'
gem 'feedzirra'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'
gem 'bourbon'

group :development do
  gem 'sass-rails-source-maps'
end

group :development, :test do
  gem 'jasmine'
end

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# Use jquery as the JavaScript library
gem 'jquery-rails', '~> 3.0'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end
```

any ideas?

**Comment by cheald** [comment]
@morenoh149 The fix has been merged - try specifying a git URL for Sass until the next release.

**Comment by morenoh149** [comment]
@cheald yeah I went ahead and just did that :+1:
the fix is to add `gem 'sass', git: 'https://github.com/nex3/sass.git'` to your gemfile
