### ISSUE TITLE
@extend causes an error when there's a newline in the selector string

### ISSUE THREAD

**Issue by chriseppstein** [sass/sass#110]
I noticed this while editing some SCSS files with <code>$ sass --watch src:output</code> running.

haml 3.0.25

The reproduction case is this:

In your SCSS stylesheet create a rule to be extended:

```
.embolden { font-weight: bold; }
```

Then attempt to <code>@extend</code> that class with multiple selectors, organized with a line-break in the string:

```
.mousey, .mousey span,
.chicken, .chicken span {
    @extend .emolden;
}
```

While this works if all of the selectors are on a single line, it breaks when there's a line-break, returning this error:

```
  FSSM::CallbackError: update - /Users/mike/Projects/my_scss_project/scss/_partial.scss: undefined method `superselector?' for "\n":String
    Use --trace for backtrace.
```

Here's the stack trace: (minor edits to some of the path directory names, but nothing of substance)

```
mike@host ~/Projects/my_scss_project [1.8.7@scss_proj] (master) $ sass --watch scss:stylesheets --trace
>>> Sass is watching for changes. Press Ctrl-C to stop.
/Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/sequence.rb:215:in `subweave_superselector?': undefined method `superselector?' for "\n":String (NoMethodError)
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/sequence.rb:175:in `subweave'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/sequence.rb:187:in `chunks'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/sequence.rb:175:in `subweave'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/sequence.rb:141:in `weave'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/sequence.rb:140:in `map'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/sequence.rb:140:in `weave'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/sequence.rb:87:in `do_extend'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/sequence.rb:87:in `map'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/sequence.rb:87:in `do_extend'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/comma_sequence.rb:53:in `do_extend'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/comma_sequence.rb:53:in `map'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/selector/comma_sequence.rb:53:in `do_extend'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/tree/rule_node.rb:113:in `do_extend'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/tree/node.rb:172:in `do_extend'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/tree/node.rb:172:in `map'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/tree/node.rb:172:in `do_extend'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/tree/root_node.rb:30:in `render'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/plugin.rb:223:in `update_stylesheet'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/plugin.rb:88:in `update_stylesheets'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/plugin.rb:81:in `each'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/plugin.rb:81:in `update_stylesheets'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/plugin.rb:79:in `each'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/plugin.rb:79:in `update_stylesheets'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/sass/plugin.rb:142:in `watch'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/haml/exec.rb:457:in `watch_or_update'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/haml/exec.rb:360:in `process_result'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/haml/exec.rb:41:in `parse'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/../lib/haml/exec.rb:21:in `parse!'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/gems/haml-3.0.25/bin/sass:8
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/bin/sass:19:in `load'
  from /Users/mike/.rvm/gems/ruby-1.8.7-p302@scss_proj/bin/sass:19
```

[Originally filed](https://github.com/nex3/haml/issues/342) by @miketierney

**Comment by chriseppstein** [comment]
seems to work now.
