### ISSUE TITLE
Sass installation failure

### ISSUE THREAD

**Issue by ebowers** [sass/sass#1130]
I started this conversation at
https://github.com/Team-Sass/generator-style-prototype/issues/47
and was recommended to head over here. Any ideas?

---

Sorry if this is a silly question, I'm still learning to use the terminal. But when I run the yeoman generator installer, I am getting this failure with sass. Not sure what is going on, if you have a free moment I would really appreciate any help at all.

Installing sass (3.3.0.rc.4) 
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

....and then down at the bottom ....

An error occurred while installing sass (3.3.0.rc.4), and Bundler cannot
continue.
Make sure that gem install sass -v '3.3.0.rc.4' succeeds before bundling.

Exited with code: 5.
Warning: Task "exec:bundle:." failed. Use --force to continue.

**Comment by lolmaus** [comment]
Are you on Windows?

**Comment by ebowers** [comment]
Mac 10.9.1

**Comment by nex3** [comment]
Please post the entire installation log.

**Comment by ebowers** [comment]
After installing the Style Prototype package through yeoman, I try running a grunt server command and I get this error with SASS.

```
➜  testproject  grunt server
Running "server" task

Running "bundler" task

Running "exec:bundle:." (exec) task
Fetching gem metadata from https://rubygems.org/..............
Fetching gem metadata from https://rubygems.org/..
Resolving dependencies...
Installing chunky_png (1.3.0) 
Installing multi_json (1.8.4) 
Installing sass (3.3.0.rc.5) 
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/ebgd85/.rvm/rubies/ruby-1.9.3-p194/bin/ruby mkrf_conf.rb 
Ensuring you have the right version of listen installed.
Installing listen >= 1.1.0, < 2.5
Building native extensions.  This could take a while...

rake RUBYARCHDIR=/Applications/MAMP/htdocs/test-prototype/testproject/.vendor/ruby/1.9.1/extensions/x86_64-darwin-12/1.9.1/sass-3.3.0.rc.5 RUBYLIBDIR=/Applications/MAMP/htdocs/test-prototype/testproject/.vendor/ruby/1.9.1/extensions/x86_64-darwin-12/1.9.1/sass-3.3.0.rc.5
/Users/ebgd85/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:298:in `to_specs': Could not find 'rake' (>= 0) among 8 total gem(s) (Gem::LoadError)
    from /Users/ebgd85/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:309:in `to_spec'
    from /Users/ebgd85/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb:53:in `gem'
    from /Users/ebgd85/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:18:in `<main>'
    from /Users/ebgd85/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/ebgd85/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'

rake failed, exit code 1

Gem files will remain installed in /Applications/MAMP/htdocs/test-prototype/testproject/.vendor/ruby/1.9.1/gems/sass-3.3.0.rc.5 for inspection.
Results logged to /Applications/MAMP/htdocs/test-prototype/testproject/.vendor/ruby/1.9.1/extensions/x86_64-darwin-12/1.9.1/sass-3.3.0.rc.5/gem_make.out
An error occurred while installing sass (3.3.0.rc.5), and Bundler cannot
continue.
Make sure that `gem install sass -v '3.3.0.rc.5'` succeeds before bundling.
>> Exited with code: 5.
Warning: Task "exec:bundle:." failed. Use --force to continue.

Aborted due to warnings.
➜  testproject 
```

**Comment by chriseppstein** [comment]
> `Results logged to /Applications/MAMP/htdocs/test-prototype/testproject/.vendor/ruby/1.9.1/extensions/x86_64-darwin-12/1.9.1/sass-3.3.0.rc.5/gem_make.out`

Can you include the contents of that file too?

**Comment by ebowers** [comment]
```
/Users/ebgd85/.rvm/rubies/ruby-1.9.3-p194/bin/ruby mkrf_conf.rb 
Ensuring you have the right version of listen installed.
Installing listen >= 1.1.0, < 2.5
Building native extensions.  This could take a while...

rake RUBYARCHDIR=/Applications/MAMP/htdocs/test-prototype/testproject/.vendor/ruby/1.9.1/extensions/x86_64-darwin-12/1.9.1/sass-3.3.0.rc.5 RUBYLIBDIR=/Applications/MAMP/htdocs/test-prototype/testproject/.vendor/ruby/1.9.1/extensions/x86_64-darwin-12/1.9.1/sass-3.3.0.rc.5
/Users/ebgd85/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:298:in `to_specs': Could not find 'rake' (>= 0) among 8 total gem(s) (Gem::LoadError)
    from /Users/ebgd85/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:309:in `to_spec'
    from /Users/ebgd85/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb:53:in `gem'
    from /Users/ebgd85/.rvm/gems/ruby-1.9.3-p194@global/bin/rake:18:in `<main>'
    from /Users/ebgd85/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/ebgd85/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'

rake failed, exit code 1
```

**Comment by nex3** [comment]
It looks like we just need to add a dependency on Rake.

**Comment by aladine** [comment]
If you are using MacOS, most likely Xcode tool is not update yet. 
Try this link: http://stackoverflow.com/questions/19580685/installing-rails-on-mavericks

**Comment by ebowers** [comment]
@aladine updated xcode and I'm still getting the same error.
