### ISSUE TITLE
3.3.0 requires access to /usr/lib/ruby

### ISSUE THREAD

**Issue by jleclanche** [sass/sass#1154]
```
Building native extensions.  This could take a while...
ERROR:  Error installing sass-3.3.0.gem:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby mkrf_conf.rb
Failed to load /etc/gemrc because it doesn't contain valid YAML hash
/usr/lib/ruby/2.1.0/rubygems/installer.rb:620:in `verify_gem_home': You don't have write permissions for the /usr/lib/ruby/gems/2.1.0 directory. (Gem::FilePermissionError)
        from /usr/lib/ruby/2.1.0/rubygems/installer.rb:740:in `pre_install_checks'
        from /usr/lib/ruby/2.1.0/rubygems/installer.rb:213:in `install'
        from /usr/lib/ruby/2.1.0/rubygems/request_set.rb:136:in `block in install'
        from /usr/lib/ruby/2.1.0/rubygems/request_set.rb:120:in `each'
        from /usr/lib/ruby/2.1.0/rubygems/request_set.rb:120:in `install'
        from /usr/lib/ruby/2.1.0/rubygems/dependency_installer.rb:389:in `install'
        from mkrf_conf.rb:18:in `<main>'
Ensuring you have the right version of listen installed.
Installing listen >= 1.1.0, < 3.0.0

rake failed, exit code 1

Gem files will remain installed in /home/adys/aur/ruby-sass/pkg/ruby-sass/usr/lib/ruby/gems/2.1.0/gems/sass-3.3.0 for inspection.
Results logged to /home/adys/aur/ruby-sass/pkg/ruby-sass/usr/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/sass-3.3.0/gem_make.out
```

This seems to me that the 3.3.0 gem requires access to /usr, which is an awful idea as it breaks packaging. Suggestions?

**Comment by HamptonMakes** [comment]
I'm confused about this too! Rails requires that all bundled projects NOT
use native extensions at all, right?

People need XCode installed now to run Sass?

I'm confused...

**Comment by nex3** [comment]
Merging into #1163.
