### ISSUE TITLE
--watch doesn't work

### ISSUE THREAD

**Issue by mgol** [sass/sass#1157]
I get the following output:

```
$ sass --version
Sass 3.3.0 (Maptastic Maple)
$ sass --watch css/theme/source/styles.scss:css/theme/styles.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
NoMethodError: 
```

and Sass doesn't pick up changes in the file.

Output with the `--trace` option added (Sass exits immediately with this option; without it it just gets stuck on the `NoMethodError` message):

```
$ sass --watch --trace css/theme/source/styles.scss:css/theme/styles.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
/usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.3.0/lib/sass/plugin/compiler.rb:327:in `listen_to': undefined method `thread' for #<Listen::Listener:0x007fb3a43b1118> (NoMethodError)
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.3.0/lib/sass/plugin/compiler.rb:294:in `watch'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.3.0/lib/sass/plugin.rb:108:in `method_missing'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.3.0/lib/sass/exec.rb:509:in `watch_or_update'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.3.0/lib/sass/exec.rb:346:in `process_result'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.3.0/lib/sass/exec.rb:43:in `parse'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.3.0/lib/sass/exec.rb:22:in `parse!'
    from /usr/local/Cellar/ruby/2.1.1/lib/ruby/gems/2.1.0/gems/sass-3.3.0/bin/sass:13:in `<top (required)>'
    from /usr/local/opt/ruby/bin/sass:23:in `load'
    from /usr/local/opt/ruby/bin/sass:23:in `<main>'
```

If I remove the `--watch` option, everything works fine.

I'm on OS X 10.9.2, Ruby is installed via Homebrew.

**Comment by colourgarden** [comment]
Discussion going on over at #1151.

**Comment by nex3** [comment]
Duplicate of #1151.
