### ISSUE TITLE
Recursive include error

### ISSUE THREAD

**Issue by Demwunz** [sass/sass#118]
I raised an issue on [Google Groups](https://groups.google.com/d/topic/compass-users/AEURMOw2P1E/discussion) in regards to a recursive file import error. 

The error message itself was quite ambiguous : `SystemStackError on line 189 of /Library/Ruby/Gems/1.8/gems/sass-3.1.2/lib/sass/../sass/tree/node.rb: stack level too deep`

I managed to get this error with the following setup:
- ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]
- rubygems-update (1.8.5, 1.8.1)
- sass (3.1.2)
- compass (0.11.3)`

**To replicate this error**:

Create two files:
- style.scss
- omg-text.scss

In both files, import the [omg-text gem](http://rubygems.org/gems/omg-text) `@import "omg-text";`

Now try `compass compile --trace` and you should get an error message along the same lines as this:

```
/Library/Ruby/Gems/1.8/gems/sass-3.1.2/lib/sass/../sass/tree/visitors/perform.rb:47:in 'visit_root'
/Library/Ruby/Gems/1.8/gems/sass-3.1.2/lib/sass/../sass/tree/visitors/base.rb:37:in 'send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.2/lib/sass/../sass/tree/visitors/base.rb:37:in 'visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.2/lib/sass/../sass/tree/visitors/perform.rb:18:in 'visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.2/lib/sass/../sass/tree/visitors/perform.rb:7:in 'send'
/Library/Ruby/Gems/1.8/gems/sass-3.1.2/lib/sass/../sass/tree/visitors/perform.rb:7:in 'visit'
/Library/Ruby/Gems/1.8/gems/sass-3.1.2/lib/sass/../sass/tree/root_node.rb:20:in 'render'
/Library/Ruby/Gems/1.8/gems/sass-3.1.2/lib/sass/../sass/engine.rb:291:in '_render'
/Library/Ruby/Gems/1.8/gems/sass-3.1.2/lib/sass/../sass/engine.rb:238:in 'render'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/compiler.rb:133:in 'compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/compiler.rb:119:in 'timed'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/compiler.rb:132:in 'compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/logger.rb:45:in 'red'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/compiler.rb:131:in 'compile'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/compiler.rb:111:in 'compile_if_required'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/compiler.rb:98:in 'run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/compiler.rb:96:in 'each'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/compiler.rb:96:in 'run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/compiler.rb:119:in 'timed'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/compiler.rb:95:in 'run'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/commands/update_project.rb:37:in 'perform'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/commands/base.rb:18:in 'execute'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/commands/project_base.rb:19:in 'execute'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/exec/sub_command_ui.rb:43:in 'perform!'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/lib/compass/exec/sub_command_ui.rb:15:in 'run!'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/bin/compass:25
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/bin/compass:39:in 'call'
/Library/Ruby/Gems/1.8/gems/compass-0.11.3/bin/compass:39
/usr/bin/compass:19:in 'load'
/usr/bin/compass:19
```

This will continue until either the offending file is renamed.

**Comment by nex3** [comment]
Fixed by 9ffd9aff623ab3e14285ed9f65adb21a66ae4b5a.
