### ISSUE TITLE
LoadError: cannot load such file -- rb-fsevent   Use --trace for backtrace when using --watch

### ISSUE THREAD

**Issue by jshdm** [sass/sass#1191]
I get this when running `scss --watch [ dir ]`:

``` bash
$ scss --watch css/
>>> Sass is watching for changes. Press Ctrl-C to stop.
LoadError: cannot load such file -- rb-fsevent
  Use --trace for backtrace.
$ 
```

**Comment by nex3** [comment]
What do you get if you run it with `--trace`? What about if you run `scss --version`? `gem list listen`?

**Comment by jshdm** [comment]
`scss --trace css/` doesn't seem to look like an argument. Either that or I'm using it improperly, which is probably the case.

```
$ scss --trace .
/Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/engine.rb:235:in `read': Is a directory @ io_fread - . (Errno::EISDIR)
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/engine.rb:235:in `for_file'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/exec.rb:360:in `process_result'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/exec.rb:43:in `parse'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/exec.rb:22:in `parse!'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/bin/scss:13:in `<top (required)>'
    from /Users/josh/.rvm/gems/ruby-2.1.1/bin/scss:23:in `load'
    from /Users/josh/.rvm/gems/ruby-2.1.1/bin/scss:23:in `<main>'
    from /Users/josh/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/josh/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

I'm running Sass 3.3.4 (Maptastic Maple).

Also, 

```
$ gem list listen

*** LOCAL GEMS ***

```

**Comment by nex3** [comment]
You have to use `--trace` with `--watch`: `sass --trace --watch css/`.

**Comment by jshdm** [comment]
Alright, thanks. Was that just added? I always just ran `scss --watch css/`.

**Comment by lolmaus** [comment]
`sass --trace --watch css/` is not going to resolve your issue. This command will produce a meaningful stacktrace which might help @nex3 to understand the reason behind your issue.

**Comment by jshdm** [comment]
I should really go through the entire Sass documentation some day :P

When I run `scss --trace --watch css/` I get this:

```
$ sass --trace --watch css/
>>> Sass is watching for changes. Press Ctrl-C to stop.
      write css/style.css
/Users/josh/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rb-fsevent (LoadError)
    from /Users/josh/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:207:in `load_dependent_adapter'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:198:in `usable?'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:190:in `usable_and_works?'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:57:in `block in select_and_initialize'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:55:in `each'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/vendor/listen/lib/listen/adapter.rb:55:in `select_and_initialize'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/vendor/listen/lib/listen/listener.rb:291:in `initialize_adapter'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/vendor/listen/lib/listen/listener.rb:283:in `setup'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/vendor/listen/lib/listen/listener.rb:65:in `start!'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/plugin/compiler.rb:291:in `listen_to'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/plugin/compiler.rb:257:in `watch'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/plugin.rb:108:in `method_missing'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/exec.rb:509:in `watch_or_update'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/exec.rb:346:in `process_result'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/exec.rb:43:in `parse'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/lib/sass/exec.rb:22:in `parse!'
    from /Users/josh/.rvm/gems/ruby-2.1.1/gems/sass-3.3.4/bin/sass:13:in `<top (required)>'
    from /Users/josh/.rvm/gems/ruby-2.1.1/bin/sass:23:in `load'
    from /Users/josh/.rvm/gems/ruby-2.1.1/bin/sass:23:in `<main>'
    from /Users/josh/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /Users/josh/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by lolmaus** [comment]
Please also share your `Gemfile` and `Gemfile.lock`. Please put them on http://gist.github.com/ rather than quoting in comment body.

**Comment by jshdm** [comment]
I'm not using a Gemfile in the project I'm working with.

**Comment by elhenro** [comment]
I am having the exact same problem, on ruby-sass-3.5.3-1, archlinux

**Comment by trmml** [comment]
@elhenro the fix is to stop using archlinux

**Comment by elhenro** [comment]
@trmml for me the fix was using compass via pacman. Guten Tag!

**Comment by itsmontoya** [comment]
@elhenro could you explain? I'm running into this same issue on Arch linux

**Comment by itsmontoya** [comment]
Just a note from my end, I was able to resolve this by installing rb-fevent. 
```
gem install rb-fsevent
```

**Comment by tranduyhung** [comment]
On my fresh installation of Lubuntu 18.10 `gem install rb-fsevent` didn't solve the problem. I needed to

    sudo apt-get install ruby-dev
    sudo gem update --system
    sudo gem install compass

**Comment by dotconde** [comment]
Thank you @itsmontoya, `gem install rb-fsevent` worked  👏
