### ISSUE TITLE
Freezing `true` causes strange behaviour in Rails controller specs

### ISSUE THREAD

**Issue by jcoglan** [sass/sass#1210]
We are trying to upgrade Sass from an alpha release of 3.3.0 in our application. Between `3.3.0.rc.1` and `3.3.0.rc.2`, [this commit](https://github.com/nex3/sass/commit/97b036ae967bcd0b749261a02b6c4daf9f93591f) was introduced that freezes the value passed to `Sass::Script::Value::Base.new`. When the `sass` gem is loaded during Rails start-up, this causes the values `nil`, `true` and `false` to be frozen. #1179 mentioned that `nil` should not be frozen, and this has been fixed, but in recent Sass releases `true` and `false` are still frozen.

This can cause strange behaviour in other libraries. As an example, create a new Rails app (I used Rails 4.0.4), and add these gems to `Gemfile`:

``` rb
gem 'rspec'
gem 'rspec-rails'
gem 'sass', '3.3.0.rc.1'
```

You'll need to remove the version from `sass-rails` later in the file to avoid conflicts. Add this route to `config/routes.rb`:

``` rb
resources :products
```

Add this controller to `app/controllers/products_controller.rb`:

``` rb
class ProductsController < ApplicationController
  def update
    Kernel.some_method(params[:product])
    render text: 'Done'
  end
end
```

Add the following to `spec/spec_helper.rb`:

``` rb
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rspec/rails'
```

And add the following spec in `spec/controllers/products_controller_spec.rb`:

``` rb
require 'spec_helper'

describe ProductsController do
  let :image do
    path = File.join(Rails.root, 'public', 'favicon.ico')
    Rack::Test::UploadedFile.new(path, 'image/jpeg')
  end

  let :product_params do
    {'name' => 'The new product', 'image' => image, 'save' => true}
  end

  it 'filters out extraneous parameters' do
    expect(Kernel).to receive(:some_method).with(product_params)
    patch :update, id: '42', product: product_params
  end
end
```

If you run `bundle exec rspec spec/` then you'll see that this test passes.

If you edit `Gemfile` to bump `sass` to `3.3.0.rc.2`, then run `bundle update sass`, then run `bundle exec rspec spec/` again, the tests will fail.

```
$ bundle exec rspec -c spec/
F

Failures:

  1) ProductsController does a thing
     Failure/Error: patch :update, id: '42', product: product_params
       Kernel received :some_method with unexpected arguments
         expected: ({"name"=>"The new product", "image"=>#<Rack::Test::UploadedFile:0x007fe1922ba4a0 @content_type="image/jpeg", @original_filename="favicon.ico", @tempfile=#<Tempfile:/tmp/favicon.ico20140408-29830-3uveqi>>, "save"=>true})
              got: ({"name"=>"The new product", "image"=>#<Rack::Test::UploadedFile:0x007fe1922da0e8 @content_type="image/jpeg", @original_filename="favicon.ico", @tempfile=#<Tempfile:/tmp/favicon.ico20140408-29830-3uveqi>>, "save"=>true})
     # ./app/controllers/products_controller.rb:3:in `update'
     # ./spec/controllers/products_controller_spec.rb:15:in `block (2 levels) in <top (required)>'

Finished in 0.01196 seconds
1 example, 1 failure
```

The tests fail because the test adds the value `true` to the parameters, which makes Rails create a new `Rack::Test::UploadedFile` object when processing the params, making the mock expectation fail. If `true` is not frozen, the original `UploadedFile` is kept during parameter processing and the test passes. (To verify this, go back to `3.3.0.rc.1` and add `true.freeze` to the test to see it fail.)

If the `save` param is anything but `true` or `false` then the test passes.

**Comment by jcoglan** [comment]
On closer inspection, this is the point in Rails where the frozen `true` value triggers the bug: https://github.com/rails/rails/blob/v4.0.4/actionpack/lib/action_controller/test_case.rb#L194-L195
