### ISSUE TITLE
Operation not permitted @ chmod_internal

### ISSUE THREAD

**Issue by F21** [sass/sass#1215]
I upgraded to sass 3.5.5 with compass 1.0.0alpha.19 in Ubuntu 13.10.
Ruby 2.1.1 was installed using rvm.

I was previously using sass 3.2.14 with compass 0.12.3 on ruby 2.0.0.
The project lives on windows share.

For some reason, after upgrading, compile no longer works:

```
user@ubuntu:/win/project$ compass compile --trace
Errno::EPERM on line ["1165"] of /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/util.rb: Operation not permitted @ chmod_internal - /win/project/.sass-cache/b568b739dddc79d56bdcbf8c194f7d375ede40c6/account.scssc20140416-15524-19zog9q
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/util.rb:1165:in `block in atomic_create_and_write_file'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/util.rb:1164:in `synchronize'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/util.rb:1164:in `atomic_create_and_write_file'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/cache_stores/filesystem.rb:39:in `_store'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/cache_stores/base.rb:51:in `store'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/cache_stores/chain.rb:19:in `block in store'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/cache_stores/chain.rb:19:in `each'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/cache_stores/chain.rb:19:in `store'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/engine.rb:420:in `_to_tree'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/engine.rb:305:in `to_tree'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/plugin/staleness_checker.rb:184:in `tree'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/plugin/staleness_checker.rb:174:in `compute_dependencies'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/plugin/staleness_checker.rb:149:in `dependencies'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/plugin/staleness_checker.rb:166:in `block in dependency_updated?'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/plugin/staleness_checker.rb:81:in `call'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/plugin/staleness_checker.rb:81:in `stylesheet_modified_since?'
  /home/user/.rvm/gems/ruby-2.1.1/gems/sass-3.3.5/lib/sass/plugin/staleness_checker.rb:69:in `stylesheet_needs_update?'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:85:in `needs_update?'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:197:in `should_compile?'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:143:in `compile_if_required'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:129:in `block (2 levels) in run'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:127:in `each'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:127:in `block in run'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:153:in `timed'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/compiler.rb:126:in `run'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/commands/update_project.rb:49:in `perform'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/commands/base.rb:18:in `execute'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/commands/project_base.rb:19:in `execute'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/bin/compass:30:in `block in <top (required)>'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/bin/compass:44:in `call'
  /home/user/.rvm/gems/ruby-2.1.1/gems/compass-1.0.0.alpha.19/bin/compass:44:in `<top (required)>'
  /home/user/.rvm/gems/ruby-2.1.1/bin/compass:23:in `load'
  /home/user/.rvm/gems/ruby-2.1.1/bin/compass:23:in `<main>'
  /home/user/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
  /home/user/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by vinayraghu** [comment]
Hey can you try alpha 18 of compass? I am not sure but I've had similar problems getting all these gems to behave. Even when I used bundler. Using compass 1.0.0alpha.18 solved it for me

**Comment by F21** [comment]
Just went back to alpha 18 and still the same issue :(

**Comment by F21** [comment]
Just went back to 0.12.5 and sass 3.2.19 on ruby 2.0 and the problem still occurs. I wonder if it's because I have upgraded rvm.

**Comment by F21** [comment]
Went back to sass-3.2.14 and compass 0.12.3 and everything's back to normal.

Hopefully this can be resolved so that we can use it on vagrant boxes that uses window shares.

**Comment by F21** [comment]
The `chmod`ing which was introduced in 67c681b4b2446693c76ff02482b2d8717136d51a appears to be the culprit.

Source: https://github.com/nex3/sass/commit/67c681b4b2446693c76ff02482b2d8717136d51a#diff-b5c905d162ab54ac76dccba2eaa9b59aR1165
