### ISSUE TITLE
Issue with rubinus server ruby 2.1

### ISSUE THREAD

**Issue by exocode** [sass/sass#1232]
Hi there, I dont know where to post? (sass/rubinus)?

I am switching to rubinus server by adding this to my gemfile:

`ruby "2.1.0", :engine => "rbx", :engine_version => "2.2.6"`
after trying to run any task (rails server, rake, bundle install) I get this error message:

`TypeError: Superclass mismatch: Object != Sass::Script::Tree::Node`
(convinience) -> https://github.com/nex3/sass/blob/stable/lib/sass/script/tree/literal.rb

example (bundle exec rake routes)

```
rake aborted!
TypeError: Superclass mismatch: Object != Sass::Script::Tree::Node
kernel/delta/rubinius.rb:332:in `open_class_under'
kernel/delta/rubinius.rb:24:in `open_class'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
kernel/bootstrap/array.rb:66:in `each'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
kernel/bootstrap/array.rb:66:in `each'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
kernel/bootstrap/array.rb:66:in `each'
kernel/bootstrap/array.rb:66:in `each'
kernel/common/code_loader.rb:243:in `require'
kernel/common/kernel.rb:705:in `require'
kernel/common/kernel.rb:447:in `load'
kernel/common/kernel.rb:447:in `load'
kernel/delta/code_loader.rb:66:in `load_script'
kernel/delta/code_loader.rb:152:in `load_script'
kernel/loader.rb:649:in `script'
kernel/loader.rb:831:in `main'

```

Rails server delivers that:

```
An exception occurred running script/rails:

    Superclass mismatch: Object != Sass::Script::Tree::Node (TypeError)

Backtrace:

                        Rubinius.open_class_under at kernel/delta/rubinius.rb:332
                              Rubinius.open_class at kernel/delta/rubinius.rb:24
                { } in Object(Module)#__script__ at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /sass-3.2.12/lib/sass/script/literal.rb:7
                               Object#__script__ at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /sass-3.2.12/lib/sass/script/literal.rb:1
                     Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                           Kernel(Object)#require at kernel/common/kernel.rb:705
 { } in ActiveSupport::Dependencies::Loadable(Object)#require at /Users/jan/.rbenv/versions/rbx-2.2.6
                                                                 /gems/gems/activesupport-3.2.14/lib
                                                                 /active_support/dependencies.rb:251
 ActiveSupport::Dependencies::Loadable(Object)#load_dependency at /Users/jan/.rbenv/versions/rbx-2.2.6
                                                                  /gems/gems/activesupport-3.2.14/lib
                                                                  /active_support/dependencies.rb:236
 ActiveSupport::Dependencies::Loadable(Object)#require at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                          /activesupport-3.2.14/lib/active_support
                                                          /dependencies.rb:251
                               Object#__script__ at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /compass-0.12.2/lib/compass/sass_extensions
                                                    /monkey_patches/browser_support.rb:2
                     Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                           Kernel(Object)#require at kernel/common/kernel.rb:705
 { } in ActiveSupport::Dependencies::Loadable(Object)#require at /Users/jan/.rbenv/versions/rbx-2.2.6
                                                                 /gems/gems/activesupport-3.2.14/lib
                                                                 /active_support/dependencies.rb:251
 ActiveSupport::Dependencies::Loadable(Object)#load_dependency at /Users/jan/.rbenv/versions/rbx-2.2.6
                                                                  /gems/gems/activesupport-3.2.14/lib
                                                                  /active_support/dependencies.rb:236
 ActiveSupport::Dependencies::Loadable(Object)#require at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                          /activesupport-3.2.14/lib/active_support
                                                          /dependencies.rb:251
                        { } in Object#__script__ at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /compass-0.12.2/lib/compass/sass_extensions
                                                    /monkey_patches.rb:2
                                       Array#each at kernel/bootstrap/array.rb:66
                               Object#__script__ at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /compass-0.12.2/lib/compass/sass_extensions
                                                    /monkey_patches.rb:1
                     Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                           Kernel(Object)#require at kernel/common/kernel.rb:705
 { } in ActiveSupport::Dependencies::Loadable(Object)#require at /Users/jan/.rbenv/versions/rbx-2.2.6
                                                                 /gems/gems/activesupport-3.2.14/lib
                                                                 /active_support/dependencies.rb:251
 ActiveSupport::Dependencies::Loadable(Object)#load_dependency at /Users/jan/.rbenv/versions/rbx-2.2.6
                                                                  /gems/gems/activesupport-3.2.14/lib
                                                                  /active_support/dependencies.rb:236
 ActiveSupport::Dependencies::Loadable(Object)#require at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                          /activesupport-3.2.14/lib/active_support
                                                          /dependencies.rb:251
                               Object#__script__ at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /compass-0.12.2/lib/compass/sass_extensions.rb:9
                     Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                           Kernel(Object)#require at kernel/common/kernel.rb:705
 { } in ActiveSupport::Dependencies::Loadable(Object)#require at /Users/jan/.rbenv/versions/rbx-2.2.6
                                                                 /gems/gems/activesupport-3.2.14/lib
                                                                 /active_support/dependencies.rb:251
 ActiveSupport::Dependencies::Loadable(Object)#load_dependency at /Users/jan/.rbenv/versions/rbx-2.2.6
                                                                  /gems/gems/activesupport-3.2.14/lib
                                                                  /active_support/dependencies.rb:236
 ActiveSupport::Dependencies::Loadable(Object)#require at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                          /activesupport-3.2.14/lib/active_support
                                                          /dependencies.rb:251
                        { } in Object#__script__ at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /compass-0.12.2/lib/compass.rb:5
                                       Array#each at kernel/bootstrap/array.rb:66
                               Object#__script__ at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /compass-0.12.2/lib/compass.rb:4
                     Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                           Kernel(Object)#require at kernel/common/kernel.rb:705
 { } in ActiveSupport::Dependencies::Loadable(Object)#require at /Users/jan/.rbenv/versions/rbx-2.2.6
                                                                 /gems/gems/activesupport-3.2.14/lib
                                                                 /active_support/dependencies.rb:251
 ActiveSupport::Dependencies::Loadable(Object)#load_dependency at /Users/jan/.rbenv/versions/rbx-2.2.6
                                                                  /gems/gems/activesupport-3.2.14/lib
                                                                  /active_support/dependencies.rb:236
 ActiveSupport::Dependencies::Loadable(Object)#require at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                          /activesupport-3.2.14/lib/active_support
                                                          /dependencies.rb:251
                               Object#__script__ at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /compass-rails-1.0.3/lib/compass-rails.rb:1
                     Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                                   Kernel.require at kernel/common/kernel.rb:705
                 { } in Bundler::Runtime#require at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /bundler-1.6.2/lib/bundler/runtime.rb:76
                                       Array#each at kernel/bootstrap/array.rb:66
                 { } in Bundler::Runtime#require at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /bundler-1.6.2/lib/bundler/runtime.rb:72
                                       Array#each at kernel/bootstrap/array.rb:66
                        Bundler::Runtime#require at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /bundler-1.6.2/lib/bundler/runtime.rb:61
                                 Bundler.require at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /bundler-1.6.2/lib/bundler.rb:132
                                Object#__script__ at config/application.rb:13
                     Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                           Kernel(Object)#require at kernel/common/kernel.rb:705
                        { } in Object#__script__ at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /railties-3.2.14/lib/rails/commands.rb:53
                        Kernel(Rails::Server)#tap at kernel/common/kernel.rb:769
                               Object#__script__ at /Users/jan/.rbenv/versions/rbx-2.2.6/gems/gems
                                                    /railties-3.2.14/lib/rails/commands.rb:50
                     Rubinius::CodeLoader.require at kernel/common/code_loader.rb:243
                           Kernel(Object)#require at kernel/common/kernel.rb:705
                                Object#__script__ at script/rails:6
                 Rubinius::CodeLoader#load_script at kernel/delta/code_loader.rb:66
                 Rubinius::CodeLoader.load_script at kernel/delta/code_loader.rb:152
                          Rubinius::Loader#script at kernel/loader.rb:649
                            Rubinius::Loader#main at kernel/loader.rb:831
```

How can I resolve that? 

here is the main part of my gemfile:

```
source 'https://rubygems.org'

ruby "2.1.0", :engine => "rbx", :engine_version => "2.2.6"

gem 'rails', '3.2.14'

group :production do
  gem 'puma'
end

gem 'jquery-rails'
gem 'jquery-ui-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

group :assets do
  gem 'sass-rails', '~> 3.2.6'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'

  gem 'compass-960-plugin'
  gem 'jasny_bootstrap_extension_rails'
  gem 'bootstrap-select-rails'
  gem 'bootstrap-datepicker-rails'
  gem 'bootstrap-timepicker-rails'
  gem 'bootstrap-wysihtml5-rails'
  gem 'rails-bootstrap-toggle-buttons'
  gem 'bootstrap-datetimepicker-rails'
  gem 'select2-rails'
  gem 'jquery-minicolors-rails'
  gem 'modernizr-rails'
  gem 'jquery-slimscroll-rails'
end

#must be outside of assets, because of compiling issues
gem 'bootstrap-sass', "~>2.3"
gem 'compass-rails'
gem 'touchpunch-rails'
gem 'bootstrap-multiselect-rails'

group :development, :test do
  gem 'zeus', '0.13.4.pre2'
  gem 'thin'
end
```

**Comment by nex3** [comment]
Sass currently doesn't support Rubinius, due to incompatibilities like this. I'd suggest reporting this issue to Rubinius, since it's apparently an incompatibility with MRI.

**Comment by exocode** [comment]
The only reason why I try to use rubinus is, that I wanna get my app `threadsafe!`. Can you suggest me another threadsafe && production ready multithreading server, which does not interfear with sass? 

It would rescue my weekend :-)

Thank you!
