### ISSUE TITLE
Non-ASCII characters in folder path cause trouble

### ISSUE THREAD

**Issue by danielbsig** [sass/sass#1254]
Hi,

I'm storing a project in a folder which contains non-ASCII characters (Icelandic characters in my case). This causes the following error:

Errno::ENOENT: No such file or directory - c:/Users/Daniel/Documents/Projects/ce
ntrislms/.sass-cache/35061d78e5f0085d8a788d7542a73298bf7efccc/app.scssc20140520-
7316-g4138d.lock
  Use --trace for backtrace.

The error message is correct, since my project is stored in C:/Users/Daníel (notice the &iacute;, &amp;iacute; in HTML)

Is this a known issue?

**Comment by nex3** [comment]
Please re-run with `--trace` and include the results. Also, what versions of Sass and Ruby are you using?

**Comment by nordfjord** [comment]
confirmed the error
moved a project to a directory with non-ascii character "í"
ran with --trace and got

```
$ sass src/app.scss -I src/vendor --trace
c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/import_node.rb:63:in `join': incompatible character encodings: UTF-8 and CP850 (Encoding::CompatibilityError)
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/import_node.rb:63:in `import'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/import_node.rb:28:in `imported_file'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/import_node.rb:37:in `css_import?'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:217:in `visit_import'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:7:in `visit'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/tree/root_node.rb:20:in `render'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:315:in `_render'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/engine.rb:262:in `render'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/exec.rb:349:in `process_result'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/exec.rb:41:in `parse'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/lib/sass/exec.rb:21:in `parse!'
        from c:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.2.19/bin/sass:13:in`<top (required)>'
        from c:/Ruby200-x64/bin/sass:23:in `load'
        from c:/Ruby200-x64/bin/sass:23:in `<main>'
```

```
$ ruby -v
ruby 2.0.0p481 (2014-05-08) [x64-mingw32]
```

and I'm running sass at version 3.2.19

**Comment by nex3** [comment]
@nordfjord that's a different error message. That looks like your load paths are mixing UTF-8 and CP850 character encodings, which probably indicates a configuration issue on your end.
