### ISSUE TITLE
undefined method `to_css' for nil:NilClass

### ISSUE THREAD

**Issue by timfayz** [sass/sass#1260]
Hello, I get the problem with my simple code and I can't understand what do I wrong..

Code:

```
$media: (
    laptop: 'screen and (min-width:1366px)',
    tablet: 'screen and (max-width:1024px)',
    mobile: 'screen and (max-width:740px)',
  );
$grid-container: (
  media: (desktop, laptop, mobile),
);

@mixin media ($media-map, $media-name) {
  @media #{map-get($media-map, $media-name)} {
    @content;
  }
}

$devices: map-get($grid-container, media);
$i: 1;
@while $i <= length($devices) {
  $device: nth($devices, $i);
  @include media($media, $device) {
    .container {
      width:100%;
    }
  }

  $i: $i + 1 !global;
}
```

Output:

```
[Listen warning]: Change block raise an execption: undefined method `to_css' for nil:NilClass
Backtrace:
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/media_node.rb:38:in `resolved_value'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/to_css.rb:183:in `block in visit_directive'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/to_css.rb:42:in `for_node'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/to_css.rb:183:in `visit_directive'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/to_css.rb:237:in `block in visit_media'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/to_css.rb:34:in `with_tabs'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/to_css.rb:237:in `visit_media'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/base.rb:36:in `visit'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/to_css.rb:24:in `visit'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/to_css.rb:118:in `block in visit_root'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/to_css.rb:116:in `each'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/to_css.rb:116:in `visit_root'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/base.rb:36:in `visit'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/visitors/to_css.rb:24:in `visit'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/node.rb:164:in `css'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/tree/root_node.rb:20:in `render'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/engine.rb:274:in `render'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/plugin/compiler.rb:414:in `update_stylesheet'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/plugin/compiler.rb:189:in `block in update_stylesheets'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/plugin/compiler.rb:186:in `each'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/plugin/compiler.rb:186:in `update_stylesheets'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/plugin/compiler.rb:393:in `on_file_changed'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/lib/sass/plugin/compiler.rb:248:in `block in watch'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/vendor/listen/lib/listen/listener.rb:252:in `call'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/vendor/listen/lib/listen/listener.rb:252:in `on_change'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/vendor/listen/lib/listen/listener.rb:290:in `block in initialize_adapter'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/vendor/listen/lib/listen/adapters/polling.rb:48:in `call'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/vendor/listen/lib/listen/adapters/polling.rb:48:in `poll_changed_directories'
        /home/timur/.rvm/gems/ruby-2.1.2/gems/sass-3.3.7/vendor/listen/lib/listen/adapter.rb:299:in `block in start_poller'
```

What's going on?

**Comment by timfayz** [comment]
thanks!)

**Comment by aaronwng** [comment]
this bug appers again recently
Sass 3.4.18 (Selective Steve)

**Comment by chriseppstein** [comment]
@biblesyme can you please open a new issue with your stack trace and using the latest version of sass?

**Comment by aaronwng** [comment]
i opened a new issue https://github.com/sass/sass/issues/2039
