### ISSUE TITLE
ERROR -- : Listen::Change crashed!

### ISSUE THREAD

**Issue by ActionScripted** [sass/sass#1268]
Perhaps not a SASS issue, but when I try to run `sass --watch main.scss:main.css` it crashes. Output/info:

``` bash

Sarah:Desktop michael$ sass --watch main.scss:main.css
>>> Sass is watching for changes. Press Ctrl-C to stop.
E, [2014-06-04T14:19:35.273952 #4654] ERROR -- : Listen::Change crashed!
Encoding::CompatibilityError: inspected result must be ASCII only or use the same encoding with default external
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:474:in `inspect'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:474:in `inspect'
    /Library/Ruby/Gems/2.0.0/gems/listen-2.7.6/lib/listen/directory.rb:15:in `scan'
    /Library/Ruby/Gems/2.0.0/gems/listen-2.7.6/lib/listen/change.rb:34:in `change'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
E, [2014-06-04T14:19:35.347781 #4654] ERROR -- : Listen::Change crashed!
Encoding::CompatibilityError: inspected result must be ASCII only or use the same encoding with default external
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:474:in `inspect'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:474:in `inspect'
    /Library/Ruby/Gems/2.0.0/gems/listen-2.7.6/lib/listen/directory.rb:15:in `scan'
    /Library/Ruby/Gems/2.0.0/gems/listen-2.7.6/lib/listen/change.rb:34:in `change'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
^CE, [2014-06-04T14:19:37.443071 #4654] ERROR -- : Listen::Change crashed!
Celluloid::DeadActorError: attempted to call a dead actor
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/proxies/sync_proxy.rb:23:in `method_missing'
    /Library/Ruby/Gems/2.0.0/gems/listen-2.7.6/lib/listen/change.rb:18:in `change'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
E, [2014-06-04T14:19:37.458537 #4654] ERROR -- : Listen::Change crashed!
Celluloid::DeadActorError: attempted to call a dead actor
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/proxies/sync_proxy.rb:23:in `method_missing'
    /Library/Ruby/Gems/2.0.0/gems/listen-2.7.6/lib/listen/change.rb:18:in `change'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:67:in `dispatch'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
    /Library/Ruby/Gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'
Sarah:Desktop michael$ echo $LANG
en_US.UTF-8
Sarah:Desktop michael$ ruby -e "puts Encoding.default_external"
UTF-8
Sarah:Desktop michael$ sass --version
Sass 3.3.8 (Maptastic Maple)
Sarah:Desktop michael$ pwd
/Users/michael/Desktop
Sarah:Desktop michael$ sudo gem update
Updating installed gems
Nothing to update
```

**Comment by ActionScripted** [comment]
For whatever it's worth, it works just fine if I move into a folder within my desktop (e.g., ~/Desktop/foo). I realize running right on my Desktop isn't the best idea, was just trying to do a quick test/check of something.

**Comment by nex3** [comment]
Please re-file this against [guard/listen](/guard/listen) and include a link to that issue here.

**Comment by dlo** [comment]
This issue looks really similar to the one I was having while running listen for my Jekyll blog. I posted an issue on the guard/listen repo at https://github.com/guard/listen/issues/250. I think it might have something to do with unicode characters in filenames.

**Comment by ActionScripted** [comment]
Just added my info there, too

**Comment by cameron** [comment]
For anybody arriving late to the party who can't find non-ASCII characters on their filesystem, `gem update listen` might do the trick :)
