### ISSUE TITLE
Windows "Invalid Argument" error in staleness_checker and update_stylesheet

### ISSUE THREAD

**Issue by robwierzbowski** [sass/sass#1328]
While integrating Sass into gulp users are running into "Invalid Argument" errors around these two methods. The gulp plugin isn't doing anything more than running the Sass command line executable in a temporary directory, so I believe these are Sass errors. 

[First example](https://github.com/sindresorhus/gulp-ruby-sass/pull/89#issuecomment-49529151) is in `staleness_checker`: 

```
[17:43:37] gulp-ruby-sass: C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/staleness_checker.rb:65:in `mtime': Invalid argument - c:\Users\Ult\AppData\Local\Temp\gulp-ruby-sass\_14139e58-9ebe-4c0f-beca-73a65bb01ce9/app.css (Errno::EINVAL)
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/staleness_checker.rb:65:in `stylesheet_needs_update?'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:188:in `block in update_stylesheets'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:186:in `each'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:186:in `update_stylesheets'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin.rb:82:in `update_stylesheets'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:489:in `watch_or_update'
[17:43:37] gulp-ruby-sass: from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:346:in `process_result'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:43:in `parse'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:22:in `parse!'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/bin/sass:13:in `<top (required)>'
    from C:/Ruby200-x64/bin/sass:23:in `load'
    from C:/Ruby200-x64/bin/sass:23:in `<main>'
```

When bypassing `staleness_checker` by using the `--force` option, [there's a similar EINVAL error](https://github.com/sindresorhus/gulp-ruby-sass/pull/89#issuecomment-49555910) thrown by `mkdir_p`, called by `update_stylesheet`.

```
gulp-ruby-sass: C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': Invalid argument - c:\Users\Ult\AppData\Local\Temp\gulp-ruby-sass\_14139e58-9ebe-4c0f-beca-73a65bb01ce9/c: (Errno::EINVAL)
    from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
    from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
    from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
    from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
    from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:203:in `each'
    from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:365:in `update_stylesheet'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:189:in `block in update_stylesheets'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:186:in `each'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:186:in `update_stylesheets'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin.rb:82:in `update_stylesheets'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:489:in `watch_or_update'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:346:in `process_result'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:43:in `parse'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:22:in `parse!'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/bin/sass:13:in `<top (required)>'
    from C:/Ruby200-x64/bin/sass:23:in `load'
    from C:/Ruby200-x64/bin/sass:23:in `<main>'
```

My guess is a path is being contaminated with the wrong style path separators for Windows somewhere along the line. [Jekyll had a similar issue](https://github.com/jekyll/jekyll/issues/1948) a while ago. I don't have a Windows computer to debug on at the moment, so any help would be appreciated. 

The arguments to node's `fs.spawn()` being used to run Sass are: 

```
sass, [
 '--no-cache',
  '--trace',
  '--force',
  '--cache-location',
  'f:\\Ultradius\\.sass-cache',
  '--update',
  'c:\\Users\\Ult\\AppData\\Local\\Temp\\gulp-ruby-sass:c:\\Users\\Ult\\AppData\\Local\\Temp\\gulp-ruby-sass\\_14139e58-9ebe-4c0f-beca-73a65bb01ce9',
  '--load-path',
  'scss'
]
```

which is the equivalent of

```
sass
--no-cache
--trace
--force
--cache-location
f:\Ultradius\.sass-cache
--update
c:\Users\Ult\AppData\Local\Temp\gulp-ruby-sass:c:\Users\Ult\AppData\Local\Temp\gulp-ruby-sass\_14139e58-9ebe-4c0f-beca-73a65bb01ce9
--load-path
scss
```

**Comment by UltCombo** [comment]
I can confirm that running these commands from the native Windows CLI result in the same errors.

**Comment by UltCombo** [comment]
@robwierzbowski :exclamation: I just noticed that if we replace all backslashes with forward slashes, it works!

I've tried that after reading your linked Jekyll thread which mentions [Ruby normalizing the path separators to forward slashes](https://github.com/jekyll/jekyll/issues/1948#issuecomment-32447533). I'm not sure but, IIRC, Sass recommends always using forward slashes.

**Comment by robwierzbowski** [comment]
Do they! Well then, let's close this issue and normalize all those file paths :D.

**Comment by robwierzbowski** [comment]
Closing, noting that if it's not documented it would be nice to.

**Comment by nex3** [comment]
Sass should always accept native-style paths.

@UltCombo can you confirm whether `File.mtime()` fails on Windows-style paths (or paths with mixed backslash and forward-slash separators) fails on Windows in general?

**Comment by UltCombo** [comment]
@nex3 This seems to be a rather localized issue.

I've only managed to reproduce it using the `--update` option and with a path containing an upper case letter. In this case, the drive letter is being appended at the end of the path.

Test cases:

```
C:\tests\gulp-ruby-sass_A>sass --update "c:\tests\gulp-ruby-sass_A\scss:c:\tests\gulp-ruby-sass_A\css" --trace
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/staleness_checker.rb:65:in `mtime': Invalid argument
 - c:\tests\gulp-ruby-sass_A\css/c:/tests/gulp-ruby-sass_A/scss/app.css (Errno::EINVAL)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/staleness_checker.rb:65:in `stylesheet_
needs_update?'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:188:in `block in update_sty
lesheets'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:186:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:186:in `update_stylesheets'

        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin.rb:82:in `update_stylesheets'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:489:in `watch_or_update'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:346:in `process_result'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:43:in `parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:22:in `parse!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/bin/sass:13:in `<top (required)>'
        from C:/Ruby200-x64/bin/sass:23:in `load'
        from C:/Ruby200-x64/bin/sass:23:in `<main>'
```

It emits a different error with `--force`, but due to the same reason I believe.

```
C:\tests\gulp-ruby-sass_A>sass --update "c:\tests\gulp-ruby-sass_A\scss:c:\tests\gulp-ruby-sass_A\css" --trace --force
  directory c:\tests\gulp-ruby-sass_A\css/c:/tests/gulp-ruby-sass_A/scss
C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': Invalid argument - c:\tests\gulp-ruby-sass_A\css/c: (Errno::E
INVAL)
        from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
        from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
        from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
        from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
        from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:203:in `each'
        from C:/Ruby200-x64/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:365:in `update_stylesheet'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:189:in `block in update_sty
lesheets'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:186:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:186:in `update_stylesheets'

        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin.rb:82:in `update_stylesheets'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:489:in `watch_or_update'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:346:in `process_result'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:43:in `parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:22:in `parse!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/bin/sass:13:in `<top (required)>'
        from C:/Ruby200-x64/bin/sass:23:in `load'
        from C:/Ruby200-x64/bin/sass:23:in `<main>'
```

Weirdly enough, the error does not happen when using a relative path from a current working directory path which contains an upper case letter.

```
C:\tests\gulp-ruby-sass_A>sass --update "scss:css" --trace
      write css/app.css
```

Tests ran on Sass 3.3.10, Ruby 2.0.0p481 x64, Windows 7 Ultimate x64.

**Comment by nex3** [comment]
@UltCombo That looks like Sass is having trouble splitting apart the two paths. We do have logic for doing that correctly on absolute Windows paths, though, and the original error doesn't include the appended path. It's especially strange that the order of the two paths is reversed.

Can you try applying the following diff, run the example again, and include the output here?

``` diff
diff --git a/lib/sass/exec.rb b/lib/sass/exec.rb
index 0acfa97..6ddb221 100644
--- a/lib/sass/exec.rb
+++ b/lib/sass/exec.rb
@@ -451,12 +451,15 @@ MSG

         dirs, files = @args.map {|name| split_colon_path(name)}.
           partition {|i, _| File.directory? i}
+        p [:dirs, dirs, :files, files]
         files.map! do |from, to|
           to ||= from.gsub(/\.[^.]*?$/, '.css')
           sourcemap = Util.sourcemap_name(to) if @options[:sourcemap]
           [from, to, sourcemap]
         end
+        p [:mapped_files, files]
         dirs.map! {|from, to| [from, to || from]}
+        p [:mapped_dirs, dirs]
         ::Sass::Plugin.options[:template_location] = dirs

         ::Sass::Plugin.on_updated_stylesheet do |_, css, sourcemap|
@@ -524,6 +527,7 @@ MSG
           one2, two = two.split(':', 2)
           one = one + ':' + one2
         end
+        p [one, two]
         return one, two
       end
```

**Comment by UltCombo** [comment]
@nex3 here it is:

```

C:\Users\Ult>sass --update "c:\tests\gulp-ruby-sass_A\scss:c:\tests\gulp-ruby-sass_A\css" --trace
["c:\\tests\\gulp-ruby-sass_A\\scss", "c:\\tests\\gulp-ruby-sass_A\\css"]
["c:\\tests\\gulp-ruby-sass_A\\scss", "c:\\tests\\gulp-ruby-sass_A\\css"]
[:dirs, [["c:\\tests\\gulp-ruby-sass_A\\scss", "c:\\tests\\gulp-ruby-sass_A\\css"]], :files, []]
[:mapped_files, []]
[:mapped_dirs, [["c:\\tests\\gulp-ruby-sass_A\\scss", "c:\\tests\\gulp-ruby-sass_A\\css"]]]
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/staleness_checker.rb:65:in `mtime': Invalid argument
 - c:\tests\gulp-ruby-sass_A\css/c:/tests/gulp-ruby-sass_A/scss/app.css (Errno::EINVAL)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/staleness_checker.rb:65:in `stylesheet_
needs_update?'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:188:in `block in update_sty
lesheets'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:186:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:186:in `update_stylesheets'

        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin.rb:82:in `update_stylesheets'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:492:in `watch_or_update'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:346:in `process_result'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:43:in `parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:22:in `parse!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/bin/sass:13:in `<top (required)>'
        from C:/Ruby200-x64/bin/sass:23:in `load'
        from C:/Ruby200-x64/bin/sass:23:in `<main>'
```

**Comment by UltCombo** [comment]
Doing some more tests now, the error is reproducible even on paths without capital letters -- the problem seems to be with `--update` and absolute paths.

**Comment by nex3** [comment]
@UltCombo I think I've figured out what's going on here. Try this diff and let me know if it fixes the issue:

``` diff
diff --git a/lib/sass/plugin/compiler.rb b/lib/sass/plugin/compiler.rb
index 72a5d41..d22f8a0 100644
--- a/lib/sass/plugin/compiler.rb
+++ b/lib/sass/plugin/compiler.rb
@@ -176,7 +176,7 @@ module Sass::Plugin
       template_location_array.each do |template_location, css_location|
         Sass::Util.glob(File.join(template_location, "**", "[^_]*.s[ca]ss")).sort.each do |file|
           # Get the relative path to the file
-          name = file.sub(template_location.to_s.sub(/\/*$/, '/'), "")
+          name = file.sub(template_location.to_s.sub(/[\/\\]*$/, '/'), "")
           css = css_filename(name, css_location)
           sourcemap = Sass::Util.sourcemap_name(css) if engine_options[:sourcemap]
           individual_files << [file, css, sourcemap]
```

**Comment by UltCombo** [comment]
@nex3 Thanks for the effort, but same error still.

I should have some free time later today, I could try to trace this issue but I'm not really a Ruby guy. I'll be up for a remote debugging with TeamViewer or similar if you'd like.

**Comment by nex3** [comment]
Hmm, strange. Try this:

``` diff
diff --git a/lib/sass/plugin/compiler.rb b/lib/sass/plugin/compiler.rb
index 72a5d41..5f5d667 100644
--- a/lib/sass/plugin/compiler.rb
+++ b/lib/sass/plugin/compiler.rb
@@ -174,11 +174,13 @@ module Sass::Plugin
       staleness_checker = StalenessChecker.new(engine_options)

       template_location_array.each do |template_location, css_location|
+        p [:template_location, template_location, :css_location, css_location]
         Sass::Util.glob(File.join(template_location, "**", "[^_]*.s[ca]ss")).sort.each do |file|
           # Get the relative path to the file
           name = file.sub(template_location.to_s.sub(/\/*$/, '/'), "")
           css = css_filename(name, css_location)
           sourcemap = Sass::Util.sourcemap_name(css) if engine_options[:sourcemap]
+          p [:glob_file, file, :relative, name, :css, css, :sourcemap, sourcemap]
           individual_files << [file, css, sourcemap]
         end
       end
```

**Comment by UltCombo** [comment]
@nex3 

```

C:\tests\gulp-ruby-sass_A>sass --update "c:\tests\gulp-ruby-sass_A\scss:c:\tests\gulp-ruby-sass_A\css" --trace
["c:\\tests\\gulp-ruby-sass_A\\scss", "c:\\tests\\gulp-ruby-sass_A\\css"]
["c:\\tests\\gulp-ruby-sass_A\\scss", "c:\\tests\\gulp-ruby-sass_A\\css"]
[:dirs, [["c:\\tests\\gulp-ruby-sass_A\\scss", "c:\\tests\\gulp-ruby-sass_A\\css"]], :files, []]
[:mapped_files, []]
[:mapped_dirs, [["c:\\tests\\gulp-ruby-sass_A\\scss", "c:\\tests\\gulp-ruby-sass_A\\css"]]]
[:template_location, "c:\\tests\\gulp-ruby-sass_A\\scss", :css_location, "c:\\tests\\gulp-ruby-sass_A\\css"]
[:glob_file, "c:/tests/gulp-ruby-sass_A/scss/app.scss", :relative, "c:/tests/gulp-ruby-sass_A/scss/app.scss", :css, "c:\
\tests\\gulp-ruby-sass_A\\css/c:/tests/gulp-ruby-sass_A/scss/app.css", :sourcemap, nil]
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/staleness_checker.rb:65:in `mtime': Invalid argument
 - c:\tests\gulp-ruby-sass_A\css/c:/tests/gulp-ruby-sass_A/scss/app.css (Errno::EINVAL)
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/staleness_checker.rb:65:in `stylesheet_
needs_update?'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:190:in `block in update_sty
lesheets'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:188:in `each'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin/compiler.rb:188:in `update_stylesheets'

        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/plugin.rb:82:in `update_stylesheets'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:492:in `watch_or_update'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:346:in `process_result'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:43:in `parse'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/lib/sass/exec.rb:22:in `parse!'
        from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.3.10/bin/sass:13:in `<top (required)>'
        from C:/Ruby200-x64/bin/sass:23:in `load'
        from C:/Ruby200-x64/bin/sass:23:in `<main>'
```

I'm still using Sass 3.3.10, I can upgrade to 3.3.12 or bleeding edge if you'd like.

**Comment by nex3** [comment]
Okay, pretty sure I've actually got it this time:

``` diff
diff --git a/lib/sass/plugin/compiler.rb b/lib/sass/plugin/compiler.rb
index 72a5d41..ae43366 100644
--- a/lib/sass/plugin/compiler.rb
+++ b/lib/sass/plugin/compiler.rb
@@ -176,7 +176,8 @@ module Sass::Plugin
       template_location_array.each do |template_location, css_location|
         Sass::Util.glob(File.join(template_location, "**", "[^_]*.s[ca]ss")).sort.each do |file|
           # Get the relative path to the file
-          name = file.sub(template_location.to_s.sub(/\/*$/, '/'), "")
+          name = Sass::Util.pathname(file).relative_path_from(
+            Sass::Util.pathname(template_location.to_s)).to_s
           css = css_filename(name, css_location)
           sourcemap = Sass::Util.sourcemap_name(css) if engine_options[:sourcemap]
           individual_files << [file, css, sourcemap]
```

**Comment by UltCombo** [comment]
@nex3 yay, you got it! It works now, good job.

**Comment by nex3** [comment]
Sweet! Just in time for the next stable release, too.
