### ISSUE TITLE
rake assets:precompile failing in 3.4.2 (works in 3.4.1) with bootstrap-sass gem

### ISSUE THREAD

**Issue by remomueller** [sass/sass#1406]
I'm getting the following error when using 3.4.2 (doesn't occur in 3.4.1)

This occurs when I run: `bundle exec rake assets:precompile`

The line that breaks is [util.rb:670](https://github.com/sass/sass/blob/3.4.2/lib/sass/util.rb#L670)

```
rake aborted!
Errno::ENOENT: No such file or directory @ realpath_rec - /usr/local/rvm/gems/ruby-2.1.2/gems/bootstrap-sass-3.2.0.1/assets/images
  (in /Users/remo/code/ruby/slice/app/assets/stylesheets/application.css.scss)
/usr/local/rvm/gems/ruby-2.1.2/gems/sass-3.4.2/lib/sass/util.rb:670:in `realpath'
/usr/local/rvm/gems/ruby-2.1.2/gems/sass-3.4.2/lib/sass/util.rb:670:in `realpath'
/usr/local/rvm/gems/ruby-2.1.2/gems/sass-3.4.2/lib/sass/util.rb:670:in `realpath'
/usr/local/rvm/gems/ruby-2.1.2/gems/sass-3.4.2/lib/sass/importers/filesystem.rb:16:in `initialize'
/usr/local/rvm/gems/ruby-2.1.2/gems/sass-rails-5.0.0.beta1/lib/sass/rails/importer.rb:11:in `initialize'
/usr/local/rvm/gems/ruby-2.1.2/gems/sass-rails-5.0.0.beta1/lib/sass/rails/template.rb:16:in `new'
/usr/local/rvm/gems/ruby-2.1.2/gems/sass-rails-5.0.0.beta1/lib/sass/rails/template.rb:16:in `block in evaluate'
/usr/local/rvm/gems/ruby-2.1.2/gems/sass-rails-5.0.0.beta1/lib/sass/rails/template.rb:16:in `map'
/usr/local/rvm/gems/ruby-2.1.2/gems/sass-rails-5.0.0.beta1/lib/sass/rails/template.rb:16:in `evaluate'
/usr/local/rvm/gems/ruby-2.1.2/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/context.rb:197:in `block in evaluate'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/context.rb:194:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/context.rb:194:in `evaluate'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/processed_asset.rb:12:in `initialize'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/base.rb:374:in `new'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/base.rb:374:in `block in build_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/base.rb:395:in `circular_call_protection'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/base.rb:373:in `build_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/index.rb:94:in `block in build_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/caching.rb:58:in `cache_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/index.rb:93:in `build_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/base.rb:287:in `find_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/index.rb:61:in `find_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/bundled_asset.rb:16:in `initialize'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/base.rb:377:in `new'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/base.rb:377:in `build_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/index.rb:94:in `block in build_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/caching.rb:58:in `cache_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/index.rb:93:in `build_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/base.rb:287:in `find_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/index.rb:61:in `find_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/manifest.rb:211:in `block in find_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/manifest.rb:257:in `benchmark'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/manifest.rb:210:in `find_asset'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/manifest.rb:119:in `block in compile'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/manifest.rb:118:in `each'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/sprockets/manifest.rb:118:in `compile'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-rails-3.0.0.beta1/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-2.12.1/lib/rake/sprocketstask.rb:146:in `with_logger'
/usr/local/rvm/gems/ruby-2.1.2/gems/sprockets-rails-3.0.0.beta1/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

If you need more information, please ask, thanks!

**Comment by remomueller** [comment]
Just an update. This is no longer occuring after doing the following:

Downgrade to 3.4.1 in `Gemfile`
clear compiled assets in `public/assets`
running `bundle exec rake assets:precompile`
Upgrading back to 3.4.2 in `Gemfile`
clear compiled assets in `public/assets`
running `bundle exec rake assets:precompile` (now works correctly).

Not quite sure what caused the issue, but closing this for the time being, and am now no longer able to reproduce this.

Thanks.

**Comment by boone** [comment]
I saw this today too. bootstrap-sass 2.3.2.2 is returning a bad path [here](https://github.com/twbs/bootstrap-sass/blob/v2.3.2.2/lib/bootstrap-sass.rb#L22) for my app.

Looks like sass ~~master~~ stable is OK, this [new commit](https://github.com/sass/sass/commit/46bb5d4aeae0c121413a295f7840ec50f21fc951) seems to solve it. @nex3 can that be released?

**Comment by chrisnicola** [comment]
Same issue occurs with sass-rails 5.0.0.beta1 and sass 3.4.2 just in case anyone else has this problem.

**Comment by navarr** [comment]
3.4.2 is pretty broken because of this.  Would be great to have this fixed.

**Comment by chrisnicola** [comment]
My workaround for now is to use the stable branch directly which seems to be fixed.

**Comment by wbotelhos** [comment]
Hi,

Problem: all assets folders were removed via Capistrano during the deploy.
Solution: avoid it or recreate all folders like the following:

``` bash
mkdir /var/www/my_app/current/app/assets/stylesheets
mkdir /var/www/my_app/current/app/assets/javascripts
mkdir /var/www/my_app/current/app/assets/images
mkdir /var/www/my_app/current/app/assets/fonts
```
