### ISSUE TITLE
Rails asset precompile fails as of version 3.4.2

### ISSUE THREAD

**Issue by moiristo** [sass/sass#1410]
The following error occurs when I try to precompile a rails app using sass 3.4.2. I found out this problem doesn't occur in 3.4.1. The rails app contains several Rails engines, but the precompile fails even if the application.css.sass is an empty file in the root project. Not sure if this is relevant though, please let me know if you need more information..

```
[12:15:01] ~/projects/npo_portal $ rake assets:precompile                                                                                                                          
/Users/nedforce/.rvm/rubies/ruby-2.1.1/bin/ruby /Users/nedforce/.rvm/gems/ruby-2.1.1@rails/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
rake aborted!
Errno::ENOENT: No such file or directory @ realpath_rec - /Users/nedforce/projects/vendor
  (in /Users/nedforce/projects/npo_portal/app/assets/stylesheets/application.css.sass)
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sass-3.4.2/lib/sass/util.rb:670:in `realpath'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sass-3.4.2/lib/sass/util.rb:670:in `realpath'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sass-3.4.2/lib/sass/util.rb:670:in `realpath'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sass-3.4.2/lib/sass/importers/filesystem.rb:16:in `initialize'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sass-3.4.2/lib/sass/engine.rb:192:in `new'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sass-3.4.2/lib/sass/engine.rb:192:in `block in normalize_options'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sass-3.4.2/lib/sass/engine.rb:190:in `map'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sass-3.4.2/lib/sass/engine.rb:190:in `normalize_options'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sass-3.4.2/lib/sass/engine.rb:256:in `initialize'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sass-rails-3.2.6/lib/sass/rails/template_handlers.rb:106:in `new'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sass-rails-3.2.6/lib/sass/rails/template_handlers.rb:106:in `evaluate'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/context.rb:193:in `block in evaluate'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `each'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/context.rb:190:in `evaluate'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/processed_asset.rb:12:in `initialize'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `new'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:249:in `block in build_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:270:in `circular_call_protection'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:248:in `build_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/bundled_asset.rb:16:in `initialize'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `new'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:252:in `build_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/index.rb:93:in `block in build_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/caching.rb:19:in `cache_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/index.rb:92:in `build_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:169:in `find_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/index.rb:60:in `find_asset'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/actionpack-3.2.19/lib/sprockets/static_compiler.rb:19:in `block in compile'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:219:in `block in each_logical_path'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:196:in `each_entry'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:204:in `block in each_file'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:203:in `each_file'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/sprockets-2.2.2/lib/sprockets/base.rb:217:in `each_logical_path'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/actionpack-3.2.19/lib/sprockets/static_compiler.rb:18:in `compile'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/actionpack-3.2.19/lib/sprockets/assets.rake:56:in `internal_precompile'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/actionpack-3.2.19/lib/sprockets/assets.rake:70:in `block (3 levels) in <top (required)>'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/actionpack-3.2.19/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
Tasks: TOP => assets:precompile:primary
(See full trace by running task with --trace)
rake aborted!
Command failed with status (1): [/Users/nedforce/.rvm/rubies/ruby-2.1.1/bin...]
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/actionpack-3.2.19/lib/sprockets/assets.rake:12:in `ruby_rake_task'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/actionpack-3.2.19/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/gems/actionpack-3.2.19/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/bin/ruby_executable_hooks:15:in `eval'
/Users/nedforce/.rvm/gems/ruby-2.1.1@rails/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by tagliala** [comment]
same here. pretty complex environment... in less. I'm using scss only to generate icon sprites.

```
[RailsAdmin] RailsAdmin initialization disabled by default. Pass SKIP_RAILS_ADMIN_INITIALIZER=false if you need it.
rake aborted!
Errno::ENOENT: No such file or directory - /Users/USER/dev/vendor
  (in /Users/USER/dev/APP_REPO/app/assets/stylesheets/icon-sprites/flag-icons.css.scss)
```

I notice that sass is trying to access this folder: `/Users/USER/dev/vendor` that does not exist and as you can see it is outside of my app repository

3.4.1 is fine

**Comment by boone** [comment]
See also #1406. The latest ~~master~~ stable commit seems to solve the problem for me.

**Comment by tagliala** [comment]
ah sorry, didn't spot that one because it is closed

**Comment by boone** [comment]
I think it's a legitimate issue, so please leave this open.

**Comment by bodrovis** [comment]
Same here, downgrading to 3.4.1 solves the problem.

**Comment by moiristo** [comment]
Sorry indeed, I didn't know about #1406 either :) I'll downgrade for now until the change described in #1406 has been released.
