### ISSUE TITLE
--watch. Error: NoMethodError: undefined method `zero?' for nil:NilClass

### ISSUE THREAD

**Issue by Tom910** [sass/sass#1412]
Win 8.1 64bit
ruby 2.0.0p481 (2014-05-08) [i386-mingw32]
Sass 3.4.2
When the command is:
sass --watch test.scss 
This error is:
NoMethodError: undefined method `zero?' for nil:NilClass

```
C:/Ruby200/lib/ruby/2.0.0/pathname.rb:25:in `block in <class:Pathname>': undefin
ed method `zero?' for nil:NilClass (NoMethodError)
    from C:/Ruby200/lib/ruby/2.0.0/pathname.rb:504:in `[]'
    from C:/Ruby200/lib/ruby/2.0.0/pathname.rb:504:in `relative_path_from'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/importers/f
ilesystem.rb:76:in `public_url'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/engine.rb:3
59:in `block in _render_with_sourcemap'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/util.rb:482
:in `silence_warnings'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/engine.rb:3
57:in `_render_with_sourcemap'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/engine.rb:2
85:in `render_with_sourcemap'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/plugin/comp
iler.rb:490:in `update_stylesheet'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/plugin/comp
iler.rb:215:in `block in update_stylesheets'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/plugin/comp
iler.rb:209:in `each'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/plugin/comp
iler.rb:209:in `update_stylesheets'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/plugin/comp
iler.rb:294:in `watch'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/plugin.rb:1
08:in `method_missing'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/exec/sass_s
css.rb:349:in `watch_or_update'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/exec/sass_s
css.rb:50:in `process_result'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/exec/base.r
b:40:in `parse'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/lib/sass/exec/base.r
b:19:in `parse!'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/sass-3.4.2/bin/sass:13:in `<top
 (required)>'
    from C:/Ruby200/bin/sass:23:in `load'
    from C:/Ruby200/bin/sass:23:in `<main>'
```

test.scss:

```
a {
  color: white;

  &:hover {
    color: black;
  }
}
```

**Comment by Tom910** [comment]
Sass 3.3.9 (Maptastic Maple) - normally executes this command:

```
a {
  color: white; }
  a:hover {
    color: black; }
```

**Comment by Jero786** [comment]
I have the same issue:

ruby 2.0.0p451 (2014-02-24) [x64-mingw32]
Sass 3.4.2 (Selective Steve)
Node v0.10.31
npm .4.23
Win: 8.1

**Comment by Tom910** [comment]
Thank you! problem solved
