### ISSUE TITLE
Compass fails to compile after upgrade to 3.4 Sass

### ISSUE THREAD

**Issue by minneapolisdan** [sass/sass#1415]
**Here's the trace of my error:**

```
 Dan-Moriarty-MacBookPro-3:umn_subtheme danmoriarty$ compass watch --trace
>>> Compass is watching for changes. Press Ctrl-C to Stop.
Errno::ENOENT on line ["670"] of /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/util.rb: 
No such file or directory - /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sassy-strings-1.0.0/stylesheets
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/util.rb:670:in `realpath'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/util.rb:670:in `realpath'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/importers/filesystem.rb:16:in `initialize'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/engine.rb:192:in `new'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/engine.rb:192:in `block in normalize_options'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/engine.rb:190:in `map'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/engine.rb:190:in `normalize_options'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/plugin/staleness_checker.rb:52:in `initialize'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/plugin/compiler.rb:203:in `new'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/plugin/compiler.rb:203:in `update_stylesheets'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/sass-3.4.2/lib/sass/plugin/compiler.rb:294:in `watch'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/compass-1.0.1/lib/compass/sass_compiler.rb:46:in `watch!'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/compass-1.0.1/lib/compass/commands/watch_project.rb:41:in `perform'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/compass-1.0.1/lib/compass/commands/base.rb:18:in `execute'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/compass-1.0.1/lib/compass/commands/project_base.rb:19:in `execute'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/compass-1.0.1/bin/compass:30:in `block in <top (required)>'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/compass-1.0.1/bin/compass:44:in `call'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/gems/compass-1.0.1/bin/compass:44:in `<top (required)>'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/bin/compass:23:in `load'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/bin/compass:23:in `<main>'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `eval'
  /Users/danmoriarty/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `<main>'

My gemfile:

      # Sass, Compass and extensions.
  gem 'sass'                    # Sass.
  gem 'sass-globbing'           # Import Sass files based on globbing pattern.
  gem 'compass', '~>1.0'                # Framework built on Sass.
  gem 'compass-validator'       # So you can `compass validate`.
  gem 'compass-normalize'       # Compass version of normalize.css.
  gem 'compass-rgbapng'         # Turns rgba() into .png's for backwards compatibility.
  gem 'zen-grids'               # Zen Grids grid framework.
  gem 'singularitygs'           # Alternative grid framework.
  gem 'toolkit'                 # Compass utility from the fabulous Snugug.
  gem 'breakpoint'              # Manages CSS media queries.
  gem 'oily_png'                # Faster Compass sprite generation.
  gem 'css_parser'              # Helps `compass stats` output statistics.
  gem 'compass-import-once'
```

**My gemlock file:**

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.3.6)
    breakpoint (2.0.7)
      compass (>= 0.12.1)
      sass (>= 3.2.0)
    celluloid (0.15.2)
      timers (~> 1.1.0)
    celluloid-io (0.15.0)
      celluloid (>= 0.15.0)
      nio4r (>= 0.5.0)
    chunky_png (1.3.1)
    coderay (1.1.0)
    color-schemer (0.2.8)
      compass-blend-modes (~> 0.0.2)
    compass (1.0.1)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.1)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-blend-modes (0.0.2)
      compass
    compass-core (1.0.1)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    compass-normalize (1.5)
      compass (>= 0.12.0)
    compass-rgbapng (0.2.1)
      chunky_png (>= 0.8.0)
      compass (>= 0.10.0)
    compass-validator (3.0.1)
    css_parser (1.3.5)
      addressable
    em-websocket (0.5.0)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.5.3)
    eventmachine (1.0.3)
    ffi (1.9.3)
    formatador (0.2.4)
    guard (2.6.0)
      formatador (>= 0.2.4)
      listen (~> 2.7)
      lumberjack (~> 1.0)
      pry (>= 0.9.12)
      thor (>= 0.18.1)
    guard-compass (1.1.0)
      compass (>= 0.10.5)
      guard (~> 2.0)
    guard-livereload (2.1.2)
      em-websocket (~> 0.5)
      guard (~> 2.0)
      multi_json (~> 1.8)
    guard-shell (0.6.1)
      guard (>= 1.1.0)
    http_parser.rb (0.5.3)
    listen (2.7.1)
      celluloid (>= 0.15.2)
      celluloid-io (>= 0.15.0)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
    lumberjack (1.0.5)
    method_source (0.8.2)
    multi_json (1.9.2)
    nio4r (1.0.0)
    oily_png (1.1.1)
      chunky_png (~> 1.3.0)
    pry (0.9.12.6)
      coderay (~> 1.0)
      method_source (~> 0.8)
      slop (~> 3.4)
    rb-fchange (0.0.6)
      ffi
    rb-fsevent (0.9.4)
    rb-inotify (0.9.3)
      ffi (>= 0.5.0)
    sass (3.4.2)
    sass-globbing (1.1.0)
      sass (>= 3.1)
    sassy-strings (1.0.0)
      compass (>= 0.12.2)
    singularitygs (1.1.2)
      breakpoint (>= 2.0.1)
      compass (>= 0.12.2)
      sass (>= 3.2.1)
    slop (3.5.0)
    thor (0.19.1)
    timers (1.1.0)
    toolkit (1.3.8)
      breakpoint (>= 2.0.6)
      color-schemer (>= 0.2.7)
      compass (>= 0.12.2)
      sassy-strings (>= 1.0.0)
      singularitygs (>= 1.1.2)
    yajl-ruby (1.2.0)
    zen-grids (1.4)
      sass (>= 3.1)

PLATFORMS
  ruby

DEPENDENCIES
  breakpoint
  compass (~> 1.0)
  compass-import-once
  compass-normalize
  compass-rgbapng
  compass-validator
  css_parser
  guard
  guard-compass
  guard-livereload
  guard-shell
  oily_png
  rb-fchange
  rb-fsevent
  rb-inotify (~> 0.9)
  sass
  sass-globbing
  singularitygs
  toolkit
  yajl-ruby
  zen-grids
```

**and from my config.rb file**

```
# Require any additional compass plugins installed on your system.
require 'compass-normalize'
require 'rgbapng'
require 'toolkit'
require 'sass-globbing'
require 'zen-grids'
```

**Comment by nex3** [comment]
Duplicate of #1406.
