### ISSUE TITLE
Regression with `sass-convert --recursive` 

### ISSUE THREAD

**Issue by pascalduez** [sass/sass#1435]
Following of SassDoc/sassdoc#183

Regression introduced starting Sass `3.4.2` 

`$ sass -v`

```
Sass 3.4.4 (Selective Steve)
```

`$ sass-convert -R -F sass -T scss src dest`

```
directory dest
    convert src/indented.sass
    create dest/indented.scss
Errno::EISDIR: Is a directory - src
  Use --trace for backtrace.
```

No `.scss` file created.

Whereas

`$ sass -v`

```
Sass 3.4.1 (Selective Steve)
```

`$ sass-convert -R -F sass -T scss src dest`

```
directory dest
    convert src/indented.sass
    overwrite dest/indented.scss
```

All fine.

**Comment by KittyGiraudel** [comment]
Confirmed.

**Comment by SteveBenner** [comment]
I’ve tried many variations of the command, with different options, and invariably I get an error like this one:

``` bash
$ sass-convert -R --from scss --to sass source/ source/ --trace
  convert source//_base.scss
  overwrite source//_base.sass
/Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/engine.rb:229:in `read': Is a directory @ io_fread - source/ (Errno::EISDIR)
        from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/engine.rb:229:in `for_file'
        from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/exec/sass_convert.rb:247:in `block in process_file'
from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/util.rb:492:in `silence_sass_warnings'
        from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/exec/sass_convert.rb:241:in `process_file'
        from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/exec/sass_convert.rb:210:in `block in process_directory'
from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/util.rb:633:in `block in glob'
        from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/util.rb:633:in `glob'
        from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/util.rb:633:in `glob'
from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/exec/sass_convert.rb:187:in `process_directory'
        from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/exec/sass_convert.rb:40:in `process_result'
        from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/exec/base.rb:40:in `parse'
from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/lib/sass/exec/base.rb:19:in `parse!'
        from /Users/user/.gem/ruby/2.1.2/gems/sass-3.4.3/bin/sass-convert:12:in `<top (required)>'
        from /Users/user/.gem/ruby/2.1.2/bin/sass-convert:23:in `load'
from /Users/user/.gem/ruby/2.1.2/bin/sass-convert:23:in `<main>’
```
