### ISSUE TITLE
Error installing Sass 

### ISSUE THREAD

**Issue by skube** [sass/sass#1489]
I'm not that familiar with Ruby or Sass but trying to install it gave the following error:

```
➜ ~ > sudo gem install sass
Password:
Fetching: sass-3.4.6.gem (100%)
Successfully installed sass-3.4.6
1 gem installed
➜ ~ > sass -v
/usr/local/Cellar/ruby/2.1.2_2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/usr/local/Cellar/ruby/2.1.2_2/lib/ruby/2.1.0/x86_64-darwin12.0/digest/sha1.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (LoadError)
  Referenced from: /usr/local/Cellar/ruby/2.1.2_2/lib/ruby/2.1.0/x86_64-darwin12.0/digest/sha1.bundle
  Reason: image not found - /usr/local/Cellar/ruby/2.1.2_2/lib/ruby/2.1.0/x86_64-darwin12.0/digest/sha1.bundle
    from /usr/local/Cellar/ruby/2.1.2_2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/sass-3.3.9/lib/sass/engine.rb:2:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.1.2_2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.1.2_2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/sass-3.3.9/lib/sass.rb:104:in `<top (required)>'
    from /usr/local/Cellar/ruby/2.1.2_2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/Cellar/ruby/2.1.2_2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/ruby/gems/2.1.0/gems/sass-3.3.9/bin/sass:8:in `rescue in <top (required)>'
    from /usr/local/lib/ruby/gems/2.1.0/gems/sass-3.3.9/bin/sass:5:in `<top (required)>'
    from /usr/local/bin/sass:23:in `load'
    from /usr/local/bin/sass:23:in `<main>'
```

**Comment by nex3** [comment]
This looks like a problem with your Ruby installation. Try reinstalling that.
