### ISSUE TITLE
label:not(.class) causing exception

### ISSUE THREAD

**Issue by rk** [sass/sass#1502]
Try compiling the following SCSS in SASS 3.4.6, I'm using Ruby 2.1.4. This issue does not occur in SASS 3.4.5.

``` scss
label:not(.class) {
  font-weight: bold;

  .required {
    color: red;
  }
}
```

Produces (full trace):

```
(sass):2: Invalid CSS after "bold": expected expression (e.g. 1px, bold), was ";" (Sass::SyntaxError)
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/scss/parser.rb:1163:in `expected'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/script/lexer.rb:220:in `expected!'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/script/parser.rb:601:in `assert_done'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/script/parser.rb:63:in `parse'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/script/parser.rb:183:in `parse'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/script.rb:27:in `parse'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:1120:in `parse_script'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:710:in `parse_property'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:681:in `parse_property_or_rule'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:647:in `parse_line'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:525:in `build_tree'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:544:in `block in append_children'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:543:in `each'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:543:in `append_children'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:534:in `block in build_tree'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:527:in `each'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:527:in `build_tree'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:544:in `block in append_children'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:543:in `each'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:543:in `append_children'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:396:in `_to_tree'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/engine.rb:268:in `render'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/exec/sass_scss.rb:404:in `run'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/exec/sass_scss.rb:62:in `process_result'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/exec/base.rb:52:in `parse'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/exec/base.rb:19:in `parse!'
    from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/bin/sass:13:in `<top (required)>'
    from /usr/local/var/rbenv/versions/2.1.4/bin/sass:23:in `load'
    from /usr/local/var/rbenv/versions/2.1.4/bin/sass:23:in `<main>'
```

If you switch up the properties (even the nested class) the error won't change. Switch the `font-weight` to `display: block` and the same message is produced.

In my actual stylesheet I get the following when compiling with Compass:

```
(/usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/sass-3.4.6/lib/sass/selector/abstract_sequence.rb:96:in `block in _specificity': undefined method `specificity' for [:not(.checkbox)]:Array)
```

I've tried to get a trace from Compass, but it won't give me any more details than that.

**Comment by cimmanon** [comment]
Duplicate of https://github.com/sass/sass/issues/1476

**Comment by rk** [comment]
Good eye. I searched but forgot that Github now adds default search filters to issues.
