### ISSUE TITLE
--watch Error after installing Bundler: undefined method 'join'

### ISSUE THREAD

**Issue by heymarkreeves** [sass/sass#1529]
I've never seen this error before. I've had, and been using Sass for a while on the command line. Today, for the first time, I installed Bundler for github-pages and now this is popping up whether I run Sass through bundler or on its own.

Sass does compile files, whether I'm just running Sass or using `--watch`, but when using `--watch` it breaks on this error, so it's unable to watch.

```
$ sass --watch _ui/css:ui/css --trace
>>> Sass is watching for changes. Press Ctrl-C to stop.
  directory ui/css
      write ui/css/styles.css
      write ui/css/styles.css.map
/Library/Ruby/Gems/2.0.0/gems/sass-3.4.8/lib/sass/plugin/compiler.rb:402:in `block in listen_to': undefined method `join' for #<ConditionVariable:0x007ff2cc1a3d50> (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.8/lib/sass/plugin/compiler.rb:402:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.8/lib/sass/plugin/compiler.rb:402:in `listen_to'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.8/lib/sass/plugin/compiler.rb:338:in `watch'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.8/lib/sass/plugin.rb:108:in `method_missing'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.8/lib/sass/exec/sass_scss.rb:370:in `watch_or_update'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.8/lib/sass/exec/sass_scss.rb:50:in `process_result'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.8/lib/sass/exec/base.rb:52:in `parse'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.8/lib/sass/exec/base.rb:19:in `parse!'
    from /Library/Ruby/Gems/2.0.0/gems/sass-3.4.8/bin/sass:13:in `<top (required)>'
    from /usr/bin/sass:23:in `load'
    from /usr/bin/sass:23:in `<main>'
```

**Comment by heymarkreeves** [comment]
I just had the following for CSS:

```
* {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: 16px;
}
```

**Comment by nex3** [comment]
I think this is the same as #1527.

**Comment by heymarkreeves** [comment]
Hi, @nex3: Thanks for the quick reply! However, I don't see anything in #1527 that addresses the error I'm seeing or offers me a solution. I'm trying to restore my Sass workflow to working order. Please reopen this issue or direct me to a solution I can implement? Thanks!

**Comment by e2** [comment]
@circa1977  - You can simply downgrade and freeze your Listen gem version, see: https://github.com/guard/listen/issues/275#issuecomment-63697308

**Comment by heymarkreeves** [comment]
That did it. Thanks!
