### ISSUE TITLE
Compass not compiling SASS 3.4.8 

### ISSUE THREAD

**Issue by timbog80** [sass/sass#1533]
NoMethodError on line ["402"] of /var/lib/gems/1.9.1/gems/sass-3.4.8/lib/sass/plugin/compiler.rb: undefined method `join' for nil:NilClass
Run with --trace to see the full backtrace

ran with --trace:

```
/var/lib/gems/1.9.1/gems/sass-3.4.8/lib/sass/plugin/compiler.rb:402:in `each'
  /var/lib/gems/1.9.1/gems/sass-3.4.8/lib/sass/plugin/compiler.rb:402:in `listen_to'
  /var/lib/gems/1.9.1/gems/sass-3.4.8/lib/sass/plugin/compiler.rb:338:in `watch'
  /var/lib/gems/1.9.1/gems/compass-1.0.1/lib/compass/sass_compiler.rb:46:in `watch!'
  /var/lib/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/watch_project.rb:41:in `perform'
  /var/lib/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/base.rb:18:in `execute'
  /var/lib/gems/1.9.1/gems/compass-1.0.1/lib/compass/commands/project_base.rb:19:in `execute'
  /var/lib/gems/1.9.1/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:43:in `perform!'
  /var/lib/gems/1.9.1/gems/compass-1.0.1/lib/compass/exec/sub_command_ui.rb:15:in `run!'
  /var/lib/gems/1.9.1/gems/compass-1.0.1/bin/compass:30:in `block in <top (required)>'
  /var/lib/gems/1.9.1/gems/compass-1.0.1/bin/compass:44:in `call'
  /var/lib/gems/1.9.1/gems/compass-1.0.1/bin/compass:44:in `<top (required)>'
  /usr/local/bin/compass:23:in `load'
  /usr/local/bin/compass:23:in `<main>'
```

**Comment by popara** [comment]
I would +1 this one. 

Sass is behaving weird these days...

**Comment by nex3** [comment]
This is #1527. 3.4.9 will include a fix.
