### ISSUE TITLE
Broken on ruby 1.9.0 due to lack of absolute_path

### ISSUE THREAD

**Issue by fvsch** [sass/sass#1611]
Trying to run Sass 3.4.9 on a server with Ruby 1.9.0. Fails with this trace:

```
$ ruby1.9 -v
ruby 1.9.0 (2008-06-20 revision 17482) [x86_64-linux]
$ sass -v
Sass 3.4.9 (Selective Steve)
$ sass input.scss output.css --trace
/var/lib/gems/1.9.0/gems/sass-3.4.9/lib/sass/util.rb:1208:in `absolute_path': undefined method `absolute_path' for File:Class (NoMethodError)
        from /var/lib/gems/1.9.0/gems/sass-3.4.9/lib/sass/importers/filesystem.rb:70:in `public_url'
        from /var/lib/gems/1.9.0/gems/sass-3.4.9/lib/sass/engine.rb:359:in `block in _render_with_sourcemap'
        from /var/lib/gems/1.9.0/gems/sass-3.4.9/lib/sass/util.rb:482:in `silence_warnings'
        from /var/lib/gems/1.9.0/gems/sass-3.4.9/lib/sass/engine.rb:357:in `_render_with_sourcemap'
        from /var/lib/gems/1.9.0/gems/sass-3.4.9/lib/sass/engine.rb:285:in `render_with_sourcemap'
        from /var/lib/gems/1.9.0/gems/sass-3.4.9/lib/sass/exec/sass_scss.rb:396:in `run'
        from /var/lib/gems/1.9.0/gems/sass-3.4.9/lib/sass/exec/sass_scss.rb:62:in `process_result'
        from /var/lib/gems/1.9.0/gems/sass-3.4.9/lib/sass/exec/base.rb:52:in `parse'
        from /var/lib/gems/1.9.0/gems/sass-3.4.9/lib/sass/exec/base.rb:19:in `parse!'
        from /var/lib/gems/1.9.0/gems/sass-3.4.9/bin/sass:13:in `<top (required)>'
        from /usr/local/bin/sass:19:in `load'
        from /usr/local/bin/sass:19:in `<main>'
```

Apparently the File class has `absolute_path` starting from ruby 1.9**.1**.

```
$ ruby1.9 -e "File.absolute_path('.')"
-e:1:in `<main>': undefined method `absolute_path' for File:Class (NoMethodError)
```

In `lib/sass/util.rb` the code checks for "not 1.8" and assumes it can use `absolute_path` then:

``` ruby
# A cross-platform implementation of `File.absolute_path`.
#
# @param path [String]
# @param dir_string [String] The directory to consider [path] relative to.
# @return [String] The absolute version of `path`.
def absolute_path(path, dir_string = nil)
  # Ruby 1.8 doesn't support File.absolute_path.
  return File.absolute_path(path, dir_string) unless ruby1_8?
  # File.expand_path expands "~", which we don't want.
  return File.expand_path(path, dir_string) unless path[0] == ?~
  File.expand_path(File.join(".", path), dir_string)
end
```

Not sure if it's worth fixing this. I don't know ruby or its ecosystem so I'm not sure if anyone has ruby 1.9.0 except us.

**Comment by nex3** [comment]
Generally we only support the latest release of `1.8.x`, `1.9.x`, `2.0.x`, and `2.1.x`. Smaller releases should be backwards-comaptible, though; is there a reason you can't upgrade your server?

I'm willing to merge in a pull request that fixes this, but I'm making no promises that 1.9.0 will work otherwise or continue to work in the future.
