### ISSUE TITLE
undefined method gsub! for nil:NilClass

### ISSUE THREAD

**Issue by danwatt** [sass/sass#169]
Im trying to convert a stylesheet from a commercial Wordpress theme (http://elegantthemes.com/preview/eStore/) so I can make some modifications in a SASSy way, getting the following trace:

```
/usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/lib/sass/css.rb:197:in `block in remove_parent_refs': undefined method `gsub!' for nil:NilClass (NoMethodError)
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/lib/sass/css.rb:194:in `each'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/lib/sass/css.rb:194:in `remove_parent_refs'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/lib/sass/css.rb:81:in `build_tree'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/lib/sass/css.rb:46:in `render'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/lib/sass/exec.rb:622:in `block in process_file'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/lib/sass/util.rb:297:in `silence_sass_warnings'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/lib/sass/exec.rb:619:in `process_file'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/lib/sass/exec.rb:538:in `process_result'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/lib/sass/exec.rb:41:in `parse'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/lib/sass/exec.rb:21:in `parse!'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.7/bin/sass-convert:7:in `<top (required)>'
        from /usr/local/bin/sass-convert:19:in `load'
        from /usr/local/bin/sass-convert:19:in `<main>'
```

**Comment by chriseppstein** [comment]
please paste the snippet of css that causes this to occur.

**Comment by danwatt** [comment]
Narrowed it down to one line. Looks like the CSS was not properly formatted, there is a double comma (between strong and ul#)

 ul#secondary-menu li.current_page_item > a > strong, , ul#secondary-menu li.current-menu-item > a > strong { color:#ede7c2; }

**Comment by nex3** [comment]
I'm re-opening this; we shouldn't crash on invalid CSS, we should raise a helpful error.

**Comment by JoannaFalkowska** [comment]
I just got this error. I managed to precompile assets before on a commit which is bugged but now it seems impossible for some reason. Cleared cache and everything, but I still get the same trace:

```
rake aborted!
NoMethodError: undefined method `gsub' for nil:NilClass
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/scss/parser.rb:120:in `init_scanner!'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/scss/parser.rb:73:in `parse_media_query_list'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:895:in `parse_media_directive'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:810:in `parse_directive'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:645:in `parse_line'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:535:in `build_tree'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:554:in `block in append_children'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:553:in `each'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:553:in `append_children'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:544:in `block in build_tree'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:537:in `each'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:537:in `build_tree'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:554:in `block in append_children'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:553:in `each'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:553:in `append_children'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:406:in `_to_tree'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:309:in `to_tree'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:324:in `block in visit_import'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:88:in `block in with_import'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:115:in `with_frame'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:88:in `with_import'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:323:in `visit_import'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:79:in `block in with_base'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:115:in `with_frame'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:79:in `with_base'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:326:in `block (2 levels) in visit_import'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:326:in `map'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:88:in `block in with_import'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:115:in `with_frame'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:88:in `with_import'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:323:in `visit_import'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:79:in `block in with_base'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:115:in `with_frame'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:79:in `with_base'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:52:in `map'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:157:in `visit'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:8:in `visit'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/root_node.rb:36:in `css_tree'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/root_node.rb:20:in `render'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:278:in `render'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass/rails/template.rb:47:in `evaluate'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
/Users/joannafalkowska/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
```

Gems which may be relevant:
```
sass (3.4.20)
sass-rails (5.0.4)
```

**Comment by JoannaFalkowska** [comment]
I just got this error. I managed to precompile assets before on a commit which is bugged but now it seems impossible for some reason. Cleared cache and everything, but I still get the same trace:

```
rake aborted!
NoMethodError: undefined method `gsub' for nil:NilClass
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/scss/parser.rb:120:in `init_scanner!'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/scss/parser.rb:73:in `parse_media_query_list'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:895:in `parse_media_directive'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:810:in `parse_directive'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:645:in `parse_line'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:535:in `build_tree'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:554:in `block in append_children'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:553:in `each'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:553:in `append_children'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:544:in `block in build_tree'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:537:in `each'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:537:in `build_tree'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:554:in `block in append_children'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:553:in `each'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:553:in `append_children'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:406:in `_to_tree'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:309:in `to_tree'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:324:in `block in visit_import'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:88:in `block in with_import'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:115:in `with_frame'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:88:in `with_import'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:323:in `visit_import'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:36:in `visit'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:79:in `block in with_base'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:115:in `with_frame'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:79:in `with_base'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:158:in `visit'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:326:in `block (2 levels) in visit_import'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:326:in `map'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:88:in `block in with_import'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:115:in `with_frame'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:88:in `with_import'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:323:in `visit_import'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:36:in `visit'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:79:in `block in with_base'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:115:in `with_frame'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/stack.rb:79:in `with_base'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:158:in `visit'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:52:in `map'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:52:in `visit_children'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:36:in `block in visit'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/base.rb:36:in `visit'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:157:in `visit'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/visitors/perform.rb:8:in `visit'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/root_node.rb:36:in `css_tree'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/tree/root_node.rb:20:in `render'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-3.4.20/lib/sass/engine.rb:278:in `render'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sass-rails-5.0.4/lib/sass/rails/template.rb:47:in `evaluate'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/tilt-2.0.1/lib/tilt/template.rb:96:in `render'
.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sprockets-3.5.2/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
```

Used gems:
sass (3.4.20)
sass-rails (5.0.4)

---

EDIT: Okay I think I resolved this. I had a bad wannabe-mixin I forgot about, defined like this:

```
=margin-xs
    @media 
    [and nothing more]
```

Still there should be raised some error instead of compiling crash.

**Comment by JoannaFalkowska** [comment]
Okay I think I resolved this. I had a bad wannabe-mixin I forgot about, defined like this:

```
=margin-xs
    @media 
    [and nothing more]
```

Still there should be raised some error instead of compiling crash.

**Comment by etwillbefine** [comment]
Same issue here, when I'm trying to format long lines.

```
@media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx)
```

cannot be formatted like:

```
@media 
only screen and (-webkit-min-device-pixel-ratio: 2), only screen and (min--moz-device-pixel-ratio: 2), only screen and (-o-min-device-pixel-ratio: 2 / 1), only screen and (min-device-pixel-ratio: 2), only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx)
```

```
.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sass-3.4.18/lib/sass/scss/parser.rb:111:in `init_scanner!': undefined method `gsub' for nil:NilClass
```

I prefer a more detailed exception. Otherwise allow something like this. Media queries can be soo long :D
