### ISSUE TITLE
NoMethodError: undefined method `start' for #<Thread: . . .

### ISSUE THREAD

**Issue by ghost** [sass/sass#1766]
Dear all, I'm totaly new at sass, please help me get it working.
Thanks

After I run this:

```
sass --watch /home/masquetina/web/style.sass:/home/masquetina/style.css
```

I got this:

```
Sass is watching for changes. Press Ctrl-C to stop.
```

But then after few seconds:

```
NoMethodError: undefined method `start' for #<Thread:0xa09fba0>
  Use --trace for backtrace.
```

After I run this:

```
sass --trace --watch /home/masquetina/web/style.sass:/home/masquetina/style.css
```

I got this: 

```
/home/masquetina/.rvm/gems/ruby-2.2.2/gems/sass-3.4.15/lib/sass/plugin/compiler.rb:402:in `block in listen_to': undefined method `start' for #<Thread:0xb5aa3254> (NoMethodError)
    from /home/masquetina/.rvm/gems/ruby-2.2.2/gems/sass-3.4.15/lib/sass/plugin/compiler.rb:402:in `map'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/gems/sass-3.4.15/lib/sass/plugin/compiler.rb:402:in `listen_to'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/gems/sass-3.4.15/lib/sass/plugin/compiler.rb:338:in `watch'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/gems/sass-3.4.15/lib/sass/plugin.rb:108:in `method_missing'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/gems/sass-3.4.15/lib/sass/exec/sass_scss.rb:384:in `watch_or_update'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/gems/sass-3.4.15/lib/sass/exec/sass_scss.rb:51:in `process_result'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/gems/sass-3.4.15/lib/sass/exec/base.rb:52:in `parse'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/gems/sass-3.4.15/lib/sass/exec/base.rb:19:in `parse!'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/gems/sass-3.4.15/bin/sass:13:in `<top (required)>'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/bin/sass:23:in `load'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/bin/sass:23:in `<main>'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
    from /home/masquetina/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

I'm on Linux Mint 17.2, and ruby/gems versions are:

```
rvm list

rvm rubies

=* ruby-2.2.2 [ i686 ]

gem list

*** LOCAL GEMS ***

actionmailer (4.2.3)
actionpack (4.2.3)
actionview (4.2.3)
activejob (4.2.3)
activemodel (4.2.3)
activerecord (4.2.3)
activesupport (4.2.3)
arel (6.0.0)
bigdecimal (1.2.7, 1.2.6)
builder (3.2.2)
bundler (1.10.5)
bundler-unload (1.0.2)
celluloid-essentials (0.20.0)
celluloid-extras (0.20.0)
celluloid-fsm (0.20.0)
celluloid-pool (0.20.0)
celluloid-supervision (0.20.0)
coderay (1.1.0)
dotenv (2.0.2)
erubis (2.7.0)
executable-hooks (1.3.2)
ffi (1.9.10)
formatador (0.2.5)
gem-wrappers (1.2.7)
globalid (0.3.5)
hitimes (1.2.2)
i18n (0.7.0)
io-console (0.4.3)
json (1.8.3, 1.8.1)
listen (3.0.2)
loofah (2.0.2)
lumberjack (1.0.9)
mail (2.6.3)
method_source (0.8.2)
mime-types (2.6.1)
mini_portile (0.6.2)
minitest (5.7.0)
nenv (0.2.0)
nokogiri (1.6.6.2)
notiffany (0.0.6)
pry (0.10.1)
psych (2.0.13, 2.0.8)
rack (1.6.4)
rack-test (0.6.3)
rails (4.2.3)
rails-deprecated_sanitizer (1.0.3)
rails-dom-testing (1.0.6)
rails-html-sanitizer (1.0.2)
railties (4.2.3)
rake (10.4.2)
rb-fsevent (0.9.5)
rb-inotify (0.9.5)
rdoc (4.2.0)
rspec-logsplit (0.1.3)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sass (3.4.15)
shellany (0.0.1)
slop (4.2.0, 3.6.0)
sprockets (3.2.0)
sprockets-rails (2.3.2)
thor (0.19.1)
thread_safe (0.3.5)
timers (4.0.1)
tzinfo (1.2.2)
```

**Comment by nex3** [comment]
Thanks for reporting this! It looks like guard/listen released a new version that's incompatible with our current code. For now, you should be able to downgrade to listen 2.x as a workaround.

**Comment by ghost** [comment]
Thanks.
Later today I manage to resolve this issue by myself. I installed Ruby 2.2.1, and made it default. I did not change listen version, just Ruby.
