### ISSUE TITLE
sass-convert integration with Vim quirk

### ISSUE THREAD

**Issue by lencioni** [sass/sass#1989]
I have set Vim's `equalprg` for scss files to be:

``` vim
setlocal equalprg=sass-convert\ --to\ scss
```

Which works well for things that look like regular CSS. However, when run it on the following code:

``` scss
.my-class { @include my-mixin; }
```

it fails with the following trace:

```
(css):1: Invalid CSS after ".my-class { ": expected "}", was "@include my-mix..." (Sass::SyntaxError)
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/scss/parser.rb:1164:in `expected'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/scss/parser.rb:1098:in `expected'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/scss/parser.rb:1093:in `tok!'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/scss/parser.rb:640:in `block'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/scss/css_parser.rb:44:in `ruleset'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/scss/css_parser.rb:29:in `block_child'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/scss/parser.rb:647:in `block_contents'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/scss/css_parser.rb:21:in `block_contents'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/scss/parser.rb:117:in `stylesheet'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/scss/parser.rb:42:in `parse'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/css.rb:77:in `build_tree'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/css.rb:47:in `render'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/exec/sass_convert.rb:244:in `block in process_file'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/util.rb:503:in `silence_sass_warnings'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/exec/sass_convert.rb:241:in `process_file'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/exec/sass_convert.rb:51:in `process_result'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/exec/base.rb:52:in `parse'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/lib/sass/exec/base.rb:19:in `parse!'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/lib/ruby/gems/1.9.1/gems/sass-3.4.18/bin/sass-convert:12:in `<top (required)>'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/bin/sass-convert:23:in `load'
>-from /Users/joe_lencioni/.rbenv/versions/1.9.3-p327/bin/sass-convert:23:in `<main>'
```

After thinking about this for a bit, I realized that it probably wasn't detecting the filetype properly (I'm guessing that Vim passes content through via stdin) so it was using the default (which is `css`) and failing because `@include` is not valid CSS. I resolved this by using the `--from` argument:

``` vim
setlocal equalprg=sass-convert\ --from\ scss\ --to\ scss
```

I don't think there's anything you need to do about this (unless you wanted to make the filetype detection more robust, or perhaps improve error messaging in this case to help people do the right thing), but I figured it would be worth documenting here to help out people who might run into the same issue.

**Comment by chriseppstein** [comment]
Auto detection is not very reliable. We use the filename. the `--from` option is necessary when using std input.
