### ISSUE TITLE
Change block raise an execption: undefined method `to_tree' for nil:NilClass

### ISSUE THREAD

**Issue by nooperpudd** [sass/sass#1990]
ruby:2.3.0
sass:3.4.21

```
[Listen warning]: Change block raise an execption: undefined method `to_tree' for nil:NilClass
Did you mean?  to_r
Backtrace:
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:184:in `tree'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:174:in `compute_dependencies'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:149:in `dependencies'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:166:in `block in dependency_updated?'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:125:in `any?'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:125:in `dependencies_stale?'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:166:in `block in dependency_updated?'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:81:in `stylesheet_modified_since?'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/staleness_checker.rb:69:in `stylesheet_needs_update?'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:211:in `block in update_stylesheets'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:209:in `each'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:471:in `on_file_changed'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/lib/sass/plugin/compiler.rb:328:in `block in watch'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/vendor/listen/lib/listen/listener.rb:252:in `on_change'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/vendor/listen/lib/listen/listener.rb:290:in `block in initialize_adapter'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/vendor/listen/lib/listen/adapter.rb:254:in `report_changes'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/vendor/listen/lib/listen/adapter.rb:323:in `poll_changed_directories'
        /usr/local/lib/ruby/gems/2.3.0/gems/sass-3.4.21/vendor/listen/lib/listen/adapter.rb:299:in `block in start_poller'
```

**Comment by chriseppstein** [comment]
Thanks for the bug report. I can't reproduce it. using the latest sass and ruby 2.3. Please provide steps to reproduce.
