### ISSUE TITLE
Failed to @extend after upgrade from 3.2.19 to 3.4.22

### ISSUE THREAD

**Issue by heaven** [sass/sass#2177]
We have the next directory structure:

```
stylesheets/
-- market/
---- _bootstrap.scss
---- _bootstrap_overrides.scss
-- _bootstrap_overrides.scss
```

Here's how the "market/_bootstrap.scss" looks like (truncated for simplicity):

``` scss
// Core mixins
@import "./bootstrap_overrides";
@import "bootstrap/mixins";
@import "bootstrap/mixins/forms_patch";

// Truncated ...

// Custom
@import "bootstrap-datetimepicker";

@import "../bootstrap_overrides";
```

So we do require `market/_bootstrap_overrides`, then do require bootstrap itself and then do require our global `/bootstrap_overrides`, which has the following lines:

``` scss
input[type=radio]:checked + label {
  @extend .btn-primary;
}

input[type=radio]:focus + label {
  @extend .btn-primary:focus;
}
```

Previously this code worked fine, but now fails with the following error:

```
".radio-buttons > div > div > span input[type=radio]:focus + label" failed to @extend ".btn-primary:focus".
The selector ".btn-primary:focus" was not found.
Use "@extend .btn-primary:focus !optional" if the extend should be able to fail.
```

**Comment by nex3** [comment]
It's difficult to know what the underlying issue here is. If you can come up with a minimal reproduction that's displaying incorrect behavior, I'll be able to help you better.

That said, you should probably avoid `@extend`ing a compound selector with multiple components (like `.btn-primary:focus` regardless. That behavior is unintended and is liable to change in the future (see #1599).

**Comment by selfthinker** [comment]
I had a similar case where I thought the same was happening. It was seemingly not working in SASS version 3.4.22 but in 3.2.19.

What solved it for me was to make sure that any file using `@extend` was a **partial** (i.e. starting with an underscore). (Or, obviously, the file using the `@extend` would need to `@import` as well.)

@heaven, in your case I wonder what `./bootstrap_overrides` is. If it's a directory, make sure its contents are only partials. If it's a file, make sure it's a partial, etc.

**Comment by heaven** [comment]
Hi, it seems like it is not about `:focus`, this code also fails:

```
input[type=radio] + label {
  @extend .btn-primary;
}
```

Working on reproduction now.

**Comment by heaven** [comment]
Was able to reproduce, please check: https://github.com/heaven/sass_test

Edits:
* config/initializers/assets.rb
* app/assets/stylesheets/
* vendor/assets/stylesheets/

To run:
* git clone https://github.com/heaven/sass_test
* cd sass_test
* bundle install
* export RAILS_ENV=production
* rake assets:precompile

Produces:
```
➜  sass_test  rake assets:precompile
[tunemygc] not enabled
[Simple Form] Simple Form is not configured in the application and will use the default values. Use `rails generate simple_form:install` to generate the Simple Form configuration.
rake aborted!
Sass::SyntaxError: ".radio-buttons > div > div > span input[type=radio]:checked + label" failed to @extend ".btn-primary".
The selector ".btn-primary" was not found.
Use "@extend .btn-primary !optional" if the extend should be able to fail.
/Users/heaven/workspace/sass_test/vendor/assets/stylesheets/_bootstrap_overrides.scss:76
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sass-3.4.22/lib/sass/tree/visitors/extend.rb:62:in `block in check_extends_fired!'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sass-3.4.22/lib/sass/util/subset_map.rb:105:in `block in each_value'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sass-3.4.22/lib/sass/util/subset_map.rb:105:in `each'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sass-3.4.22/lib/sass/util/subset_map.rb:105:in `each_value'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sass-3.4.22/lib/sass/tree/visitors/extend.rb:51:in `check_extends_fired!'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sass-3.4.22/lib/sass/tree/visitors/extend.rb:16:in `visit'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sass-3.4.22/lib/sass/tree/root_node.rb:39:in `css_tree'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sass-3.4.22/lib/sass/tree/root_node.rb:20:in `render'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sass-3.4.22/lib/sass/engine.rb:281:in `render'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sass-rails-5.0.6/lib/sass/rails/template.rb:47:in `evaluate'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/tilt-2.0.5/lib/tilt/template.rb:102:in `render'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:23:in `block in call'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/utils.rb:196:in `dfs'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:24:in `call'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/base.rb:66:in `find_asset'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:142:in `block in find'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:209:in `each'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:209:in `stat_directory'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/path_utils.rb:227:in `stat_tree'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:105:in `each'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:104:in `each'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/legacy.rb:104:in `logical_paths'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:140:in `find'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:185:in `compile'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/non-stupid-digest-assets-1.0.4/lib/non-stupid-digest-assets.rb:31:in `compile_with_non_digest'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-3.7.0/lib/rake/sprocketstask.rb:147:in `with_logger'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/airbrake-5.5.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/Users/heaven/.rvm/gems/ruby-2.3.1@crm/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by heaven** [comment]
And this does work well with `gem 'sass-rails', '< 5.0.0'`.

**Comment by nex3** [comment]
Sorry, I should have been more specific. Can you reproduce this using *only SCSS files*, without any surrounding Rails or Bootstrap context?

**Comment by heaven** [comment]
I am debugging it further and it turns that the bug was actually in the older SASS gem, because if you check `vendor/assets/stylesheets/market/_bootstrap.scss` (the partial where we include bootstrap components), it has `//@import "bootstrap/buttons";` commented out, so it is supposed to fail, but does work with the older version of SASS gem.
