### ISSUE TITLE
Error raised for comments with Sprockets 4.x

### ISSUE THREAD

**Issue by marcandre** [sass/sass#2180]
Although Sass files appear to process correctly when using `Sprockets 4.0.0.beta4`,  they raise an error if I include any comment `/* anything */`.

Here's the stacktrace I get:

```
    NoMethodError:
       undefined method `find' for nil:NilClass
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sass-3.4.22/lib/sass/source/map.rb:140:in `block in to_json'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sass-3.4.22/lib/sass/source/map.rb:118:in `each'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sass-3.4.22/lib/sass/source/map.rb:118:in `to_json'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/sass_processor.rb:86:in `call'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/sass_processor.rb:32:in `call'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:84:in `call_processor'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:65:in `reverse_each'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:65:in `call_processors'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:22:in `block in <class:CompositeProcessor>'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:33:in `call'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:84:in `call_processor'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:65:in `reverse_each'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:65:in `call_processors'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/loader.rb:148:in `load_from_unloaded'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/loader.rb:59:in `block in load'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/loader.rb:324:in `fetch_asset_from_dependency_cache'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/loader.rb:43:in `load'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/cached_environment.rb:21:in `block in initialize'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/cached_environment.rb:48:in `load'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/bundle.rb:24:in `block in call'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/utils.rb:166:in `dfs'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/bundle.rb:25:in `call'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:84:in `call_processor'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:65:in `reverse_each'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/processor_utils.rb:65:in `call_processors'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/loader.rb:148:in `load_from_unloaded'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/loader.rb:59:in `block in load'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/loader.rb:324:in `fetch_asset_from_dependency_cache'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/loader.rb:43:in `load'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/cached_environment.rb:21:in `block in initialize'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/cached_environment.rb:48:in `load'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/base.rb:67:in `find_asset'
     # /Users/work/.rvm/gems/ruby-2.3.1/gems/sprockets-4.0.0.beta4/lib/sprockets/base.rb:93:in `[]'
```

https://travis-ci.org/marcandre/css_media/jobs/172002132

**Comment by nex3** [comment]
Can you reproduce this outside of a Sprockets context?

**Comment by marcandre** [comment]
Didn't try. The fact that it was content dependent made me suspect Sass, but maybe I'm wrong. In any case, I imagine that things are moving forward and you probably have tests in place for future version of sprockets, so feel free to close this if it's not actionable.
