### ISSUE TITLE
@namespace rules cause errors

### ISSUE THREAD

**Issue by taye** [sass/sass#2188]
I'm trying to use SASS to develop skins for Firefox but the `@namespace` at-rules which are used in the theme stylesheets are causing errors.

#### `.sass` files: sass works correctly but sassc fails

```sass
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul")
@namespace html url("http://www.w3.org/1999/xhtml")

browser
  background-color: #000
html|body
  background-color: #000
```

```
Error: Invalid CSS after "@namespace": expected 1 selector or at-rule, was 'url("http://www.moz'
        on line 1 of test.sass
>> @namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"
   ----------^
```

#### `.scss` files: sass and sassc both fail

```scss
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");
@namespace html url("http://www.w3.org/1999/xhtml");

browser {  background-color: #000; }
html|body { background-color: #000; }
```

```
test.scss:1: Invalid CSS after "@namespace ": expected selector or at-rule, was "url("http://www..." (Sass::SyntaxError)
        from /home/taye/.gem/ruby/2.3.0/gems/sass-3.4.22/lib/sass/scss/parser.rb:1189:in `expected'
        from /home/taye/.gem/ruby/2.3.0/gems/sass-3.4.22/lib/sass/scss/parser.rb:1125:in `expected'
        from /home/taye/.gem/ruby/2.3.0/gems/sass-3.4.22/lib/sass/scss/parser.rb:42:in `parse'
        from /home/taye/.gem/ruby/2.3.0/gems/sass-3.4.22/lib/sass/engine.rb:406:in `_to_tree'
        from /home/taye/.gem/ruby/2.3.0/gems/sass-3.4.22/lib/sass/engine.rb:281:in `render'
        from /home/taye/.gem/ruby/2.3.0/gems/sass-3.4.22/lib/sass/exec/sass_scss.rb:400:in `run'
        from /home/taye/.gem/ruby/2.3.0/gems/sass-3.4.22/lib/sass/exec/sass_scss.rb:63:in `process_result'
        from /home/taye/.gem/ruby/2.3.0/gems/sass-3.4.22/lib/sass/exec/base.rb:52:in `parse'
        from /home/taye/.gem/ruby/2.3.0/gems/sass-3.4.22/lib/sass/exec/base.rb:19:in `parse!'
        from /home/taye/.gem/ruby/2.3.0/gems/sass-3.4.22/bin/sass:13:in `<top (required)>'
        from /home/taye/.gem/ruby/2.3.0/bin/sass:23:in `load'
        from /home/taye/.gem/ruby/2.3.0/bin/sass:23:in `<main>'
```

```
Sass 3.4.22 (Selective Steve)
sassc: 3.4.0-RC1
```

**Comment by nex3** [comment]
Sassc issues should be filed at http://github.com/sass/libsass. The Ruby Sass issue does seem like a bug, though.

**Comment by nex3** [comment]
As a workaround for the second issue, you can remove the quotes:

```scss
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);
@namespace html url(http://www.w3.org/1999/xhtml);
```
