### ISSUE TITLE
uninitialized constant Sass::Deprecation

### ISSUE THREAD

**Issue by plentz** [sass/sass#2338]
Started with `v3.4.25`

```
Bundler::GemRequireError:
  There was an error while trying to load the gem 'sassc-rails'.
  Gem Load Error is: uninitialized constant Sass::Deprecation
  Backtrace for gem load error is:
  /usr/local/lib/ruby/gems/2.4.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:5:in `<class:String>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:4:in `<module:Value>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sass-3.4.25/lib/sass/script/value/string.rb:2:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc/script.rb:32:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc/script.rb:32:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc.rb:8:in `require_relative'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-1.11.2/lib/sassc.rb:8:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-rails-1.3.0/lib/sassc/rails.rb:3:in `require'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-rails-1.3.0/lib/sassc/rails.rb:3:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-rails-1.3.0/lib/sassc-rails.rb:7:in `require_relative'
  /usr/local/lib/ruby/gems/2.4.0/gems/sassc-rails-1.3.0/lib/sassc-rails.rb:7:in `<top (required)>'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.1/lib/bundler/runtime.rb:82:in `require'
```

related #2310

**Comment by nex3** [comment]
This looks like an issue with the `sassc` gem. It's selectively requiring only a few files from within the Sass gem, rather than requiring `"sass"` as a whole; this isn't a supported way of using the gem. For the most part, Sass handles its internal requires in [`engine.rb`](https://github.com/sass/sass/blob/stable/lib/sass/engine.rb#L3-L54), so any gems requiring other libraries are taking the responsibility for ensuring that all dependencies are met into their own hands.

**Comment by meowsus** [comment]
Related PR in sassc-ruby: https://github.com/sass/sassc-ruby/pull/68
