### ISSUE TITLE
weird error in heroku and local-production: no helpful message

### ISSUE THREAD

**Issue by shivabhusal** [sass/sass#2341]
I see this error in production. How can I find which file has that error so that I can fix it?

I have hundreds of `CSS`/`SCSS` files, which one to look?
Please help

> May be we should display the erroneous file in the logs to help debugging.

```ruby
 heroku run rails assets:precompile
This is the legacy Heroku CLI. Please install the new CLI from https://cli.heroku.com
Running rails assets:precompile on ⬢ app-staging... up, run.1991 (Free)
I, [2017-07-12T03:46:35.137227 #4]  INFO -- : Writing /app/public/assets/application_footer-71aa70f171cfaadee030f6b44d64b33d7b92446d7d791d1b1926aed04b7f95d2.js
I, [2017-07-12T03:46:35.137855 #4]  INFO -- : Writing /app/public/assets/application_footer-71aa70f171cfaadee030f6b44d64b33d7b92446d7d791d1b1926aed04b7f95d2.js.gz
I, [2017-07-12T03:46:39.211359 #4]  INFO -- : Writing /app/public/assets/active_admin-8f4a05166e4e3f3733b924879539581f823c7895202c31a69559fb0bd8ead8ff.css
I, [2017-07-12T03:46:39.212010 #4]  INFO -- : Writing /app/public/assets/active_admin-8f4a05166e4e3f3733b924879539581f823c7895202c31a69559fb0bd8ead8ff.css.gz
I, [2017-07-12T03:46:39.557616 #4]  INFO -- : Writing /app/public/assets/active_admin/print-87c5ffc1d869a919123bcc1dc5ec51b20bc79fd9aeab9eed77e3438c6acd4f68.css
I, [2017-07-12T03:46:39.558149 #4]  INFO -- : Writing /app/public/assets/active_admin/print-87c5ffc1d869a919123bcc1dc5ec51b20bc79fd9aeab9eed77e3438c6acd4f68.css.gz
I, [2017-07-12T03:46:54.590055 #4]  INFO -- : Writing /app/public/assets/active_admin-12a74b3ffff1babd45eaca3fef9dce6596642a2fc91eb7d5e03d69c2b8c76570.js
I, [2017-07-12T03:46:54.590366 #4]  INFO -- : Writing /app/public/assets/active_admin-12a74b3ffff1babd45eaca3fef9dce6596642a2fc91eb7d5e03d69c2b8c76570.js.gz
I, [2017-07-12T03:46:54.593642 #4]  INFO -- : Writing /app/public/assets/default_profile-2ee12d7db9dc7863f94a1a7246c8695d5df70f12f12e47ca30b8c9b08d726442.jpg
I, [2017-07-12T03:46:54.595308 #4]  INFO -- : Writing /app/public/assets/logo-9a7c06db349b9eda0d4449400215f6b169cc1dc9456337cf7d9479078249c45c.png
I, [2017-07-12T03:46:58.454696 #4]  INFO -- : Writing /app/public/assets/application-be35e1033ffef6273de78c6a1085aa0875af06bae8149c4abd3a97139784deba.js
I, [2017-07-12T03:46:58.454926 #4]  INFO -- : Writing /app/public/assets/application-be35e1033ffef6273de78c6a1085aa0875af06bae8149c4abd3a97139784deba.js.gz
rails aborted!
Sass::SyntaxError: Invalid CSS after "(min-width: ": expected expression (e.g. 1px, bold), was ") and (max-widt..."
(sass):2
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:1207:in `expected'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/script/lexer.rb:229:in `expected!'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/script/parser.rb:710:in `assert_expr'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/script/parser.rb:75:in `parse'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:1063:in `sass_script'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:473:in `query_expr'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:448:in `media_query'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:414:in `media_query_list'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/scss/parser.rb:73:in `parse_media_query_list'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:515:in `visit_media'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `visit'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `block in visit'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/stack.rb:79:in `block in with_base'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/stack.rb:115:in `with_frame'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/stack.rb:79:in `with_base'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:162:in `visit'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `map'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:171:in `block in visit_children'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:170:in `visit_children'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:190:in `visit_root'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/base.rb:36:in `visit'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:161:in `visit'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/visitors/perform.rb:10:in `visit'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/root_node.rb:36:in `css_tree'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/tree/root_node.rb:20:in `render'
/app/vendor/bundle/ruby/2.3.0/gems/sass-3.4.25/lib/sass/engine.rb:284:in `render'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/sass_compressor.rb:48:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/sass_compressor.rb:28:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/app/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/command.rb:46:in `invoke'
/app/vendor/bundle/ruby/2.3.0/gems/railties-5.1.2/lib/rails/commands.rb:16:in `<top (required)>'
/app/bin/rails:9:in `require'
/app/bin/rails:9:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)


```

**Comment by nex3** [comment]
This is an issue for the Rails asset precompiler. Sass will include filename information if it's provided, but if it's not there's not much we can do but use a default (which is what the `(sass)` line in that stack trace is).
