### ISSUE TITLE
SASS install Problem

### ISSUE THREAD

**Issue by srsandy** [sass/sass#2388]
I'm trying to install SASS on Fedora but it shows an error

ruby -v
`ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
`
gem -v
`2.6.13
`
I tired 
`sudo gem install sass --no-user-install`

It returns 

```
Building native extensions.  This could take a while...
ERROR:  Error installing sass:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/share/gems/gems/ffi-1.9.18/ext/ffi_c
/usr/bin/ruby -r ./siteconf20171016-19919-1iaq4vp.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib64
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)
	--with-ffi_c-dir
	--without-ffi_c-dir
	--with-ffi_c-include
	--without-ffi_c-include=${ffi_c-dir}/include
	--with-ffi_c-lib
	--without-ffi_c-lib=${ffi_c-dir}/lib64
	--with-libffi-config
	--without-libffi-config
	--with-pkg-config
	--without-pkg-config
/usr/share/ruby/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/share/ruby/mkmf.rb:588:in `try_cpp'
	from /usr/share/ruby/mkmf.rb:1095:in `block in have_header'
	from /usr/share/ruby/mkmf.rb:945:in `block in checking_for'
	from /usr/share/ruby/mkmf.rb:351:in `block (2 levels) in postpone'
	from /usr/share/ruby/mkmf.rb:321:in `open'
	from /usr/share/ruby/mkmf.rb:351:in `block in postpone'
	from /usr/share/ruby/mkmf.rb:321:in `open'
	from /usr/share/ruby/mkmf.rb:347:in `postpone'
	from /usr/share/ruby/mkmf.rb:944:in `checking_for'
	from /usr/share/ruby/mkmf.rb:1094:in `have_header'
	from extconf.rb:16:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib64/gems/ruby/ffi-1.9.18/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /usr/local/share/gems/gems/ffi-1.9.18 for inspection.
Results logged to /usr/local/lib64/gems/ruby/ffi-1.9.18/gem_make.out
```

Pls help me ASAP

**Comment by nex3** [comment]
It looks like you need to install the headers for libffi. I'm not sure how to do this on Fedora, though.

**Comment by VernonGrant** [comment]
@srsandy I was facing the same problem today. I was able to get the gem installed using the following. 

`sudo dnf install rubygem-sass`

**Comment by srsandy** [comment]
@VernonGrant Thanks a lot. I solved this problem a long time back.

**Comment by Santinni** [comment]
@srsandy how did you solve it, i have got the same issue on Win10. Thanks!

**Comment by srsandy** [comment]
@Santinni I installed headers for libffi  and it worked.
