### ISSUE TITLE
NoMethodError attempting call to IO#string

### ISSUE THREAD

**Issue by spdawson** [sass/sass#2414]
This failure occurs intermittently during `rails assets:precompile` when deploying to production.

The attempted call to `IO#string` occurs [here](https://github.com/sass/sass/blob/stable/lib/sass/tree/rule_node.rb#L148).

Backtrace:

```
NoMethodError: undefined method `string' for #<IO:<STDERR>>

sass-3.5.3/lib/sass/tree/rule_node.rb:148:in `block in try_to_parse_non_interpolated_rules'
sass-3.5.3/lib/sass/util.rb:459:in `silence_warnings'
sass-3.5.3/lib/sass/tree/rule_node.rb:142:in `try_to_parse_non_interpolated_rules'
sass-3.5.3/lib/sass/tree/rule_node.rb:73:in `initialize'
sass-3.5.3/lib/sass/scss/parser.rb:672:in `new'
sass-3.5.3/lib/sass/scss/parser.rb:672:in `ruleset'
sass-3.5.3/lib/sass/scss/parser.rb:696:in `block_child'
sass-3.5.3/lib/sass/scss/parser.rb:689:in `block_contents'
sass-3.5.3/lib/sass/scss/parser.rb:137:in `stylesheet'
sass-3.5.3/lib/sass/scss/parser.rb:41:in `parse'
sass-3.5.3/lib/sass/engine.rb:414:in `_to_tree'
sass-3.5.3/lib/sass/engine.rb:389:in `_render_with_sourcemap'
sass-3.5.3/lib/sass/engine.rb:307:in `render_with_sourcemap'

sprockets-4.0.0.beta6/lib/sprockets/sass_compressor.rb:53:in `call'
sprockets-4.0.0.beta6/lib/sprockets/sass_compressor.rb:30:in `call'
sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:84:in `call_processor'
sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:65:in `reverse_each'
sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:65:in `call_processors'
sprockets-4.0.0.beta6/lib/sprockets/loader.rb:144:in `load_from_unloaded'
sprockets-4.0.0.beta6/lib/sprockets/loader.rb:59:in `block in load'
sprockets-4.0.0.beta6/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
sprockets-4.0.0.beta6/lib/sprockets/loader.rb:43:in `load'
sprockets-4.0.0.beta6/lib/sprockets/cached_environment.rb:44:in `load'
sprockets-4.0.0.beta6/lib/sprockets/bundle.rb:32:in `block in call'
sprockets-4.0.0.beta6/lib/sprockets/bundle.rb:31:in `call'
sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:84:in `call_processor'
sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:65:in `reverse_each'
sprockets-4.0.0.beta6/lib/sprockets/processor_utils.rb:65:in `call_processors'
sprockets-4.0.0.beta6/lib/sprockets/loader.rb:144:in `load_from_unloaded'
sprockets-4.0.0.beta6/lib/sprockets/loader.rb:59:in `block in load'
sprockets-4.0.0.beta6/lib/sprockets/loader.rb:318:in `fetch_asset_from_dependency_cache'
sprockets-4.0.0.beta6/lib/sprockets/loader.rb:43:in `load'
sprockets-4.0.0.beta6/lib/sprockets/cached_environment.rb:44:in `load'
sprockets-4.0.0.beta6/lib/sprockets/base.rb:69:in `find_asset'
sprockets-4.0.0.beta6/lib/sprockets/base.rb:76:in `find_all_linked_assets'
sprockets-4.0.0.beta6/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'

concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
concurrent-ruby-1.0.5/lib/concurrent/promise.rb:531:in `block in realize'
concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by ahorek** [comment]
because STDERR which is used in silence_warnings isn't threadsafe, it was introduced in https://github.com/sass/sass/pull/2298
rails depricated such silencers since version 5.0

with this patch it'll be slower, but it should work... could you test it?
```
From fe667fa3e219afe83b0b57928ad06a876c5dfc83 Mon Sep 17 00:00:00 2001

---
 lib/sass/util.rb | 15 +++++++++++----
 1 file changed, 11 insertions(+), 4 deletions(-)

diff --git a/lib/sass/util.rb b/lib/sass/util.rb
index 56ba141d..70db0471 100644
--- a/lib/sass/util.rb
+++ b/lib/sass/util.rb
@@ -454,11 +454,18 @@ module Sass
     # Silence all output to STDERR within a block.
     #
     # @yield A block in which no output will be printed to STDERR
+    require 'monitor'
+    MONITOR = Monitor.new
+
     def silence_warnings
-      the_real_stderr, $stderr = $stderr, StringIO.new
-      yield
-    ensure
-      $stderr = the_real_stderr
+      MONITOR.synchronize do
+        begin
+          the_real_stderr, $stderr = $stderr, StringIO.new
+          yield
+        ensure
+          $stderr = the_real_stderr
+        end
+      end
     end

     # Silences all Sass warnings within a block.
--

 ```

unfortunatelly, I have more threading issues in combination with SASS since this PR was introduced
https://github.com/rails/sprockets/pull/469
Warning. Error encountered while saving cache 6d542b0ec0a27c05f7c7c3efa80a684c68666a63/_variables.scssc: can't dump IO

also this could be relevant https://github.com/rails/sprockets/pull/530

**Comment by GeoffTidey** [comment]
thanks @ahorek.  This has been causing a lot of issues on our build.  I've created a PR here: https://github.com/sass/sass/pull/2417
