### ISSUE TITLE
Bug? NoMethodError: undefined method `capture' in rule_node.rb:142

### ISSUE THREAD

**Issue by lobin-z0x50** [sass/sass#2499]
In Rails, exec `assets:precompile` then odd errors occurred.

anyone has an idea ?

Ruby: 2.5.0
Rails: 5.0.6
csss-rails: 5.0.6

1.
csss: 3.5.6
```
root@3bc3efdb1bdd:/var/rails# bin/rails assets:precompile
rails aborted!
NoMethodError: undefined method `capture' for #<ActiveSupport::Logger:0x00005638183431a8>
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/tree/rule_node.rb:142:in `try_to_parse_non_interpolated_rules'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/tree/rule_node.rb:73:in `initialize'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/scss/parser.rb:672:in `new'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/scss/parser.rb:672:in `ruleset'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/scss/parser.rb:696:in `block_child'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/scss/parser.rb:686:in `block_contents'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/scss/parser.rb:137:in `stylesheet'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/scss/parser.rb:41:in `parse'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/engine.rb:414:in `_to_tree'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.6/lib/sass/engine.rb:290:in `render'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-rails-5.0.6/lib/sass/rails/template.rb:47:in `evaluate'
/var/rails/vendor/bundle/ruby/2.5.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/legacy_tilt_processor.rb:25:in `call'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:23:in `block in call'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/utils.rb:200:in `dfs'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/bundle.rb:24:in `call'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:142:in `block in find'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:231:in `block in stat_tree'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `each'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:209:in `stat_directory'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/path_utils.rb:227:in `stat_tree'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `each'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `each'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/legacy.rb:104:in `logical_paths'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:140:in `find'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/var/rails/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/var/rails/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/var/rails/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/var/rails/vendor/bundle/ruby/2.5.0/gems/railties-5.0.6/lib/rails/commands.rb:18:in `<top (required)>'
/var/rails/bin/rails:9:in `require'
/var/rails/bin/rails:9:in `<top (required)>'
/var/rails/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/var/rails/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/var/rails/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/var/rails/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/var/rails/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/var/rails/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/var/rails/vendor/bundle/ruby/2.5.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/var/rails/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
root@3bc3efdb1bdd:/var/rails#
```

2.
csss: 3.5.3
```
root@3bc3efdb1bdd:/var/rails# bin/rails assets:precompile
rails aborted!
NoMethodError: undefined method `log_level' for #<ActiveSupport::Logger:0x0000564bc9b67c98>
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/logger/delayed.rb:26:in `initialize'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/logger/delayed.rb:17:in `new'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/logger/delayed.rb:17:in `install!'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:1230:in `catch_error'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:795:in `try_declaration'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:732:in `declaration_or_ruleset'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:697:in `block_child'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:686:in `block_contents'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:678:in `block'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:747:in `declaration_or_ruleset'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:697:in `block_child'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:686:in `block_contents'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:678:in `block'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:670:in `ruleset'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:696:in `block_child'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:686:in `block_contents'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:137:in `stylesheet'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/scss/parser.rb:41:in `parse'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/engine.rb:414:in `_to_tree'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-3.5.3/lib/sass/engine.rb:290:in `render'
/var/rails/vendor/bundle/ruby/2.5.0/gems/sass-rails-5.0.6/lib/sass/rails/template.rb:47:in `evaluate'
... snip ...
```

**Comment by lobin-z0x50** [comment]
After debugging, may be a problem of `sass-rails`.
I will ask in that repository.
Thank you.

**Comment by thanhnk1602** [comment]
@lobin-z0x50 I have the same issue, but can't find any solution.
Did you fix this issue?

**Comment by lobin-z0x50** [comment]
@narutoo9x I use monkey patch.
https://github.com/lobin-z0x50/sass-rails/tree/fix-odd-logger-reference

**Comment by thanhnk1602** [comment]
Wow, It works for me. Thank you so much. 👍 👍
