### ISSUE TITLE
TypeError: "1024": type 'JSString' is not a subtype of type 'Value0' migrating from legacy JS

### ISSUE THREAD

**Issue by skjnldsv** [sass/sass#3234]
## Context

Hi, I'm trying to create a `sass.SassMap` with the following data to include as a global variable in my webpack sass-loader step

```js
{
  '400': { marginTop: 66, marginW: 8, count: 3, gap: 8 },
  '700': { marginTop: 66, marginW: 8, count: 4, gap: 8 },
  '1024': { marginTop: 66, marginW: 44, count: 5, gap: 8 },
  '1280': { marginTop: 66, marginW: 44, count: 4, gap: 8 },
  '1440': { marginTop: 88, marginW: 66, count: 5, gap: 8 },
  '1600': { marginTop: 88, marginW: 66, count: 6, gap: 8 },
  '2048': { marginTop: 88, marginW: 66, count: 7, gap: 8 },
  '2560': { marginTop: 88, marginW: 88, count: 8, gap: 8 },
  '3440': { marginTop: 88, marginW: 88, count: 9, gap: 8 },
  max: { marginTop: 88, marginW: 88, count: 10, gap: 8 }
}
```

## Issues

Unfortunately, it seems to fail and I don't understand why.
I tried almost everything I could find,  like
- creating subsets for each size into an `OrderedMap` then concat to a main one
- importing the full object through `fromJS`

Every time it fails when building the sassMap with `new sass.SassMap(fromJS(sizes).toOrderedMap())`
Can anyone help me? 

Previously, this how I used to do it with the legacy js API

```js
const sass = require('sass')
const { sizes } = require('../assets/grid-sizes')

const gridConfigKeys = Object.keys(sizes)
const gridConfigMap = new sass.types.Map(gridConfigKeys.length)

gridConfigKeys.forEach((size, index) => {
	const config = sizes[size]
	const configMap = new sass.types.Map(3)

	configMap.setKey(0, new sass.types.String('count'))
	configMap.setValue(0, new sass.types.Number(config.count))
	configMap.setKey(1, new sass.types.String('marginTop'))
	configMap.setValue(1, new sass.types.Number(config.marginTop))
	configMap.setKey(2, new sass.types.String('marginW'))
	configMap.setValue(2, new sass.types.Number(config.marginW))

	gridConfigMap.setKey(index, new sass.types.String(size))
	gridConfigMap.setValue(index, configMap)
})

module.exports = `$sizes: ${gridConfigMap};`
// $sizes: (400: (count: 3, marginTop: 66, marginW: 8), 700: (count: 4, marginTop: 66, marginW: 8), 1024: (count: 5, marginTop: 66, marginW: 44), 1280: (count: 4, marginTop: 66, marginW: 44), 1440: (count: 5, marginTop: 88, marginW: 66), 1600: (count: 6, marginTop: 88, marginW: 66), 2048: (count: 7, marginTop: 88, marginW: 66), 2560: (count: 8, marginTop: 88, marginW: 88), 3440: (count: 9, marginTop: 88, marginW: 88), max: (count: 10, marginTop: 88, marginW: 88));
```

## Env

node@^14,
npm@^7
sass@1.45.2
immutable@4.0.0

## Error
```js
[webpack-cli] Failed to load '/home/admin/Docker/apps2/photos/webpack.js' config
[webpack-cli] TypeError: "1024": type 'JSString' is not a subtype of type 'Value0'
    at Object.wrapException (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:1246:17)
    at Object._failedAsCheck (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:2556:15)
    at Rti._generalAsCheckImplementation [as _as] (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:2545:9)
    at Rti._installSpecializedAsCheck (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:2484:22)
    at CastIterator.get$current (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:25909:32)
    at Object.List_List$from (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:5298:22)
    at Object.ConstantMap_ConstantMap$from (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:869:18)
    at mapClass__closure.call$2 (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:85781:31)
    at Object.Primitives_applyFunction (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:1137:30)
    at Object.Function_apply (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:5259:16)
    at _callDartFunctionFastCaptureThis (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:22972:16)
    at new sass.SassMap (/home/admin/Docker/apps2/photos/node_modules/sass/sass.dart.js:22959:18)
    at Object.<anonymous> (/home/admin/Docker/apps2/photos/src/utils/SassGridConfig.js:46:29)
    at Module._compile (/home/admin/Docker/apps2/photos/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  dartException: _TypeError {
    '__rti$_message': `TypeError: "1024": type 'JSString' is not a subtype of type 'Value0'`
  }
}

```

**Comment by jathak** [comment]
Can you provide a minimal reproduction of this?

**Comment by skjnldsv** [comment]
Hello @jathak 
Of course, here is a runkit https://runkit.com/skjnldsv/sass-typeerror-1024-type-jsstring-is-not-a-subtype-of-type-value0

![image](https://user-images.githubusercontent.com/14975046/148640583-876bf17d-d287-4f7f-b57d-725428f4d778.png)

**Comment by jathak** [comment]
It looks like your issue here is that you're passing JS strings and numbers as keys and values. `SassMap` needs to contain `SassString`s and `SassNumber`s.

**Comment by skjnldsv** [comment]
Ok, I had to go for something like that.

```js
const sass = require('sass')
const { OrderedMap } = require('immutable')

const { sizes } = require('../assets/grid-sizes')

const gridConfigKeys = Object.keys(sizes)
const gridConfigMap = OrderedMap().asMutable()

gridConfigKeys.forEach(size => {
	const config = sizes[size]
	const configMap = OrderedMap().asMutable()

	configMap.set(new sass.SassString('count'), new sass.SassNumber(config.count))
	configMap.set(new sass.SassString('marginTop'), new sass.SassNumber(config.marginTop))
	configMap.set(new sass.SassString('marginW'), new sass.SassNumber(config.marginW))

	gridConfigMap.set(new sass.SassString(size), new sass.SassMap(configMap))
})

module.exports = `$sizes: ${new sass.SassMap(gridConfigMap)};`
```
