### ISSUE TITLE
Error with jest

### ISSUE THREAD

**Issue by Mister-Hope** [sass/sass#3235]
I am updating my gulp sass plugin, and I need to run sass in jest, while I run in to a werid problem.

Below is the mininal reproduction I can provide.

The file passed when called by `ts-node`, while throwing errors when calling by jest.

Here is the file, named with `compileSync.test.ts` under `__tests__`.

```ts
import { resolve } from "path";
import { readFileSync } from "fs";
import { compileString } from "sass";

const content = readFileSync(resolve(__dirname, "scss/inheritance.scss"), {
  encoding: "utf-8",
});

console.log(content, {
  loadPaths: [resolve(__dirname, "scss")],
});

console.log(
  compileString(content, {
    loadPaths: [resolve(__dirname, "scss")],
  })
);
```

When called by jest (just `yarn jest` command)

```
PS C:\Code\gulp-sass> yarn jest
yarn run v1.22.17$ jest  console.log
    @import "includes/cats";    @import "includes/dogs";

    .error {
      border: #f00;
      background: #fdd;
    }

    .error.intrusion {
      font-size: 1.3em;
      font-weight: bold;
    }

    .badError {
      @extend .error;
      border-width: 3px;
    }
     { loadPaths: [ 'C:\\Code\\gulp-sass\\__tests__\\scss' ] }

      at Object.<anonymous> (__tests__/compileSync.spec.ts:9:9)

 FAIL  __tests__/compileSync.spec.ts
  ● Test suite failed to run
                                                                                                 
    NoSuchMethodError: method not found: 'map$1$1' (J.getInterceptor$ax(...).map$1$1 is not a function)
      ╷
    1 │ @import "includes/cats";
      │         ^^^^^^^^^^^^^^^
      ╵
      - 1:9  root stylesheet

      at Object.map$1$1$ax (node_modules/sass/sass.dart.js:24441:44)

---------------|---------|----------|---------|---------|-------------------
File           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
---------------|---------|----------|---------|---------|-------------------
All files      |       0 |        0 |       0 |       0 |
 __tests__     |       0 |        0 |       0 |       0 |
  helpers.ts   |       0 |        0 |       0 |       0 | 1-18
  test.ts      |       0 |      100 |     100 |       0 | 1-13
 dist          |       0 |        0 |       0 |       0 |
  compile.d.ts |       0 |        0 |       0 |       0 |
  index.d.ts   |       0 |        0 |       0 |       0 |
  legacy.d.ts  |       0 |        0 |       0 |       0 |
  utils.d.ts   |       0 |        0 |       0 |       0 |
 src           |       0 |        0 |       0 |       0 |
  compile.ts   |       0 |        0 |       0 |       0 | 1-192
  index.ts     |       0 |      100 |       0 |       0 | 1-5
  legacy.ts    |       0 |        0 |       0 |       0 | 1-207
  typings.d.ts |       0 |        0 |       0 |       0 |
  utils.ts     |       0 |      100 |     100 |       0 | 1
---------------|---------|----------|---------|---------|-------------------
Snapshot Summary
 › 1 snapshot file obsolete from 1 test suite. To remove it, run `yarn test -u`.
   ↳   • __tests__/__snapshots__/compileAsync.spec.ts.snap

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   1 file obsolete, 0 total
Time:        10.062 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

While when called with `ts-node` (`yarn ts-node .\__tests__\compileSync.spec.ts`)

```
yarn run v1.22.17
$ C:\Code\gulp-sass\node_modules\.bin\ts-node .\__tests__\compileSync.spec.ts
@import "includes/cats";
@import "includes/dogs";

.error {
  border: #f00;
  background: #fdd;
}

.error.intrusion {
  font-size: 1.3em;
  font-weight: bold;
}

.badError {
  @extend .error;
  border-width: 3px;
}
 { loadPaths: [ 'C:\\Code\\gulp-sass\\__tests__\\scss' ] }
{
  css: 'body {\n' +
    '  background: pink;\n' +
    '}\n' +
    '\n' +
    'body {\n' +
    '  text-align: center;\n' +
    '}\n' +
    '\n' +
    '.error, .badError {\n' +
    '  border: #f00;\n' +
    '  background: #fdd;\n' +
    '}\n' +
    '\n' +
    '.error.intrusion, .intrusion.badError {\n' +
    '  font-size: 1.3em;\n' +
    '  font-weight: bold;\n' +
    '}\n' +
    '\n' +
    '.badError {\n' +
    '  border-width: 3px;\n' +
    '}',
  loadedUrls: [
    URL {
      href: 'file:///C:/Code/gulp-sass/__tests__/scss/includes/_cats.scss',
      origin: 'null',
      protocol: 'file:',
      username: '',
      password: '',
      host: '',
      hostname: '',
      port: '',
      pathname: '/C:/Code/gulp-sass/__tests__/scss/includes/_cats.scss',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    URL {
      href: 'file:///C:/Code/gulp-sass/__tests__/scss/includes/_dogs.sass',
      origin: 'null',
      protocol: 'file:',
      username: '',
      password: '',
      host: '',
      hostname: '',
      port: '',
      pathname: '/C:/Code/gulp-sass/__tests__/scss/includes/_dogs.sass',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    }
  ]
}
Done in 1.64s.
```

I believe there are some issues here, and I dig hard, but it's hard for me to dig something out with the compiled code.

```js
    map$1$1$ax(receiver, a0, $T1) {
      return J.getInterceptor$ax(receiver).map$1$1(receiver, a0, $T1);
    },
```

Also I am not having any ideas, why sass can compile when calling by node, and faied with errors when calling by jest.

**Comment by nex3** [comment]
This is caused by facebook/jest#2549. The short explanation is that Jest breaks `instanceof` checks for built-in types by default and Sass relies on those checks, so you'll need to install `jest-environment-node-single-context` and add `'testEnvironment': 'jest-environment-node-single-context'` to your Jest configuration.

**Comment by Mister-Hope** [comment]
Appreciated
