### ISSUE TITLE
Test failure if $LANG is not set

### ISSUE THREAD

**Issue by jleclanche** [sass/sass#346]
```
Finished tests in 9.741473s, 127.1882 tests/s, 440.4878 assertions/s.

  1) Error:
test_template_renders_correctly (import_charset)(SassPluginTest):
ArgumentError: invalid byte sequence in US-ASCII
    /home/adys/src/dist/sass/test/sass/plugin_test.rb:346:in `split'
    /home/adys/src/dist/sass/test/sass/plugin_test.rb:346:in `assert_renders_correctly'
    /home/adys/src/dist/sass/test/sass/plugin_test.rb:35:in `block (2 levels) in <class:SassPluginTest>'
```

**Comment by jleclanche** [comment]
The problem is in test/sass/results/import_charset.css

**Comment by nex3** [comment]
I can't reproduce this. What OS and Ruby version are you using? What's your `Encoding.default_external`?

**Comment by jleclanche** [comment]
I can't repro anymore, but at the time I didn't have $LANG set. with en_US.UTF-8 it works fine though.

**Comment by nex3** [comment]
Closing since we can't reproduce.

**Comment by jleclanche** [comment]
well, if you run LANG= rake, it repros.

**Comment by nex3** [comment]
I see. Re-opening.

**Comment by nex3** [comment]
This has been fixed.
