### ISSUE TITLE
diverging behaviour of `@extend` with `@include meta.load-css()` and `@use`

### ISSUE THREAD

**Issue by nachtfunke** [sass/sass#3764]
I am working in a project that heavily utilises `@extend %selector`. I am in the process of moving it to sass modules, which has gone successful so far. Now I am structuring the selectors with cascade layers `@layer`, meaning that I am now having to fallback to `@include meta.load-css()`, because I can't rewrite everything to mixins - and I believe I have found some diverging behaviour with the way that pseudo-selectors work.

```scss
.something {
  &.is-that { }
}
```

```scss
.another-thing {
  @extend .something;
}
```

when I bring in both of those partials with `@use`, `.another-thing` will be written with `.is-that`, but when I load _any_ of them with `@include meta.load-css()`, any selector that is inside `.something` will not be extended. In my case, I can solve this issue because I also have `.something` available as a mixin, but I am just wondering in general, if that is supposed to happen. The [documentation](https://sass-lang.com/documentation/modules/meta/) says:

> This doesn’t make any members from the loaded module available in the current module.

But Members are defined as [functions, mixins & variables](https://sass-lang.com/documentation/at-rules/use/#loading-members), not selectors. What is going on here?

**Comment by nex3** [comment]
Can you provide a minimal reproduction of the issue you're seeing, along with the output you expect?

**Comment by digitaldonkey** [comment]
e.g 
https://stackoverflow.com/questions/70470754/how-to-extend-a-class-from-an-imported-scss
https://stackoverflow.com/questions/51480593/angular-2-extend-a-style-from-styles-scss/51480665#51480665

Both solutions only apply using SASS 2.x. Now they throw deprecation warnings regarding 3.x.

**Comment by nex3** [comment]
I'm not sure what you mean by "Sass 2.x" and "Sass 3.x". The current Dart Sass version is 1.88.0. Ruby Sass, which reached end-of-life years ago, was last released at version 3.7.4.

It's true that `@import` is deprecated, but that's not related to `@extend` at all. If you have a specific question or issue, please file a new issue. For now I'm going to close this one since the original reporter never responded with additional information.

**Comment by digitaldonkey** [comment]
"sass": "^1.54.0",

```
ERROR in ./src/react-big-calendar/view.scss (./src/react-big-calendar/view.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[3]!./src/react-big-calendar/view.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
The target selector was not found.
Use "@extend .rbc-ellipsis !optional" to avoid this error.
   ╷
32 │   @extend .rbc-ellipsis;
   │   ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/react-big-calendar/lib/sass/event.scss 32:3    load-css()
  node_modules/react-big-calendar/lib/sass/styles.scss 130:1  @use
  src/react-big-calendar/view.scss 1:1                        root stylesheet
 @ ./src/react-big-calendar/view.scss
 @ ./src/react-big-calendar/OsecBigCal.js 6:0-21
 @ ./src/react-big-calendar/LoadableCalendar.js 29:22-32:19
 @ ./src/react-big-calendar/view.js 6:0-54 14:34-50

ERROR in ./src/react-big-calendar/view.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
The target selector was not found.
Use "@extend .rbc-ellipsis !optional" to avoid this error.
   ╷
32 │   @extend .rbc-ellipsis;
   │   ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/react-big-calendar/lib/sass/event.scss 32:3    load-css()
  node_modules/react-big-calendar/lib/sass/styles.scss 130:1  @use
  src/react-big-calendar/view.scss 1:1                        root stylesheet
    at tryRunOrWebpackError (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/HookWebpackError.js:86:9)
    at __webpack_require_module__ (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5301:12)
    at __webpack_require__ (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5258:18)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5330:20
    at symbolIterator (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3485:9)
    at done (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5236:43
    at symbolIterator (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3482:9)
    at timesSync (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3463:5)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5198:16
    at symbolIterator (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3485:9)
    at timesSync (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3463:5)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5166:15
    at symbolIterator (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3485:9)
    at done (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3527:9)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5112:8
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:3531:6
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/HookWebpackError.js:67:2
    at Hook.eval [as callAsync] (eval at create (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Cache.js:111:20)
    at ItemCacheFacade.store (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/CacheFacade.js:141:15)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:3530:11
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Cache.js:95:34
    at Array.<anonymous> (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/cache/MemoryCachePlugin.js:45:13)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Cache.js:95:19
    at Hook.eval [as callAsync] (eval at create (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:19:1)
    at Cache.get (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Cache.js:79:18)
    at ItemCacheFacade.get (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/CacheFacade.js:115:15)
    at Compilation._codeGenerationModule (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:3498:9)
    at codeGen (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5100:11)
    at symbolIterator (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3482:9)
    at timesSync (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3463:5)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5130:14
    at processQueue (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/util/processAsyncTree.js:61:4)
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:454:9)
-- inner error --
Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
The target selector was not found.
Use "@extend .rbc-ellipsis !optional" to avoid this error.
   ╷
32 │   @extend .rbc-ellipsis;
   │   ^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/react-big-calendar/lib/sass/event.scss 32:3    load-css()
  node_modules/react-big-calendar/lib/sass/styles.scss 130:1  @use
  src/react-big-calendar/view.scss 1:1                        root stylesheet
    at Object.<anonymous> (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[3]!/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/src/react-big-calendar/view.scss:1:7)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:494:10
    at Hook.eval [as call] (eval at create (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/tapable/lib/Hook.js:14:14)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5303:39
    at tryRunOrWebpackError (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/HookWebpackError.js:81:7)
    at __webpack_require_module__ (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5301:12)
    at __webpack_require__ (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5258:18)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5330:20
    at symbolIterator (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3485:9)
    at done (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3527:9)
    at Hook.eval [as callAsync] (eval at create (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5236:43
    at symbolIterator (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3482:9)
    at timesSync (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3463:5)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5198:16
    at symbolIterator (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3485:9)
    at timesSync (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3463:5)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5166:15
    at symbolIterator (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3485:9)
    at done (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3527:9)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5112:8
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:3531:6
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/HookWebpackError.js:67:2
    at Hook.eval [as callAsync] (eval at create (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Cache.js:111:20)
    at ItemCacheFacade.store (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/CacheFacade.js:141:15)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:3530:11
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Cache.js:95:34
    at Array.<anonymous> (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/cache/MemoryCachePlugin.js:45:13)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Cache.js:95:19
    at Hook.eval [as callAsync] (eval at create (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:19:1)
    at Cache.get (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Cache.js:79:18)
    at ItemCacheFacade.get (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/CacheFacade.js:115:15)
    at Compilation._codeGenerationModule (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:3498:9)
    at codeGen (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5100:11)
    at symbolIterator (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3482:9)
    at timesSync (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/neo-async/async.js:3463:5)
    at /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/Compilation.js:5130:14
    at processQueue (/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/webpack/lib/util/processAsyncTree.js:61:4)
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:454:9)

Generated code for /Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[3]!/Users/tho/htdocs/ddev-wordpress/wp-content/plugins/open-source-event-calendar/blocks/src/react-big-calendar/view.scss
1 | throw new Error("Module build failed (from ./node_modules/sass-loader/dist/cjs.js):\nThe target selector was not found.\nUse \"@extend .rbc-ellipsis !optional\" to avoid this error.\n\u001b[34m   ╷\u001b[0m\n\u001b[34m32 │\u001b[0m   \u001b[31m@extend .rbc-ellipsis\u001b[0m;\n\u001b[34m   │\u001b[0m \u001b[31m  ^^^^^^^^^^^^^^^^^^^^^\u001b[0m\n\u001b[34m   ╵\u001b[0m\n  node_modules/react-big-calendar/lib/sass/event.scss 32:3    load-css()\n  node_modules/react-big-calendar/lib/sass/styles.scss 130:1  @use\n  src/react-big-calendar/view.scss 1:1                        root stylesheet");
 @ ./src/react-big-calendar/OsecBigCal.js 6:0-21
 @ ./src/react-big-calendar/LoadableCalendar.js 29:22-32:19
 @ ./src/react-big-calendar/view.js 6:0-54 14:34-50

webpack 5.98.0 compiled with 2 errors in 2708 ms
```

The .rbs-ellipsis is in the entry point file and can't be extended. 
I can't upgrade to latest sass, feel free to close if it's *fixed* in current version. 

So maybe this provides required info.

**Comment by nex3** [comment]
A year-and-a-half old issue is not the place to be reporting this. Please file **a new issue** if you believe you've found a new error.

This error message doesn't give me any information on what your actual Sass stylesheets look like. If you want to report an issue, you'll need to include a *minimal* reproduction, which means something that only uses the Sass CLI, not any build system or framework integration.

**Comment by digitaldonkey** [comment]
Someone closed it unresolved. Your issue to ignore it.
