### ISSUE TITLE
Sass 3.2.2 fails tests on jruby

### ISSUE THREAD

**Issue by graaff** [sass/sass#563]
With jruby 1.6.7.2 (ruby-1.8.7-p357) (2012-05-17 fffffff) (OpenJDK 64-Bit Server VM 1.6.0_24) [linux-amd64-java] I'm seeing a test failure with sass 3.2.2:

```
  1) Failure:
test_template_renders_correctly (filename_fn)(SassPluginTest)
    [/var/tmp/portage/dev-ruby/sass-3.2.2/work/jruby/sass-3.2.2/test/sass/plugin_test.rb:398:in `assert_renders_correctly'
     org/jruby/RubyArray.java:1615:in `each'
     org/jruby/RubyEnumerable.java:951:in `each_with_index'
     /var/tmp/portage/dev-ruby/sass-3.2.2/work/jruby/sass-3.2.2/test/sass/plugin_test.rb:396:in `assert_renders_correctly'
     /var/tmp/portage/dev-ruby/sass-3.2.2/work/jruby/sass-3.2.2/test/sass/plugin_test.rb:48:in `test_template_renders_correctly (filename_fn)'
     org/jruby/RubyProc.java:270:in `call'
     org/jruby/RubyKernel.java:2076:in `send'
     org/jruby/RubyArray.java:1615:in `each'
     org/jruby/RubyArray.java:1615:in `each']:
template: filename_fn
line:     1.
<"filename { imported: /test/sass/templates/_filename_fn_import.scss; }"> expected but was
<"filename { imported: /_filename_fn_import.scss; }">.
```

All tests pass on both ruby 1.8.7 and ruby 1.9.3.

**Comment by nex3** [comment]
25a95fdf73d0cd889bea82157ab376cf41b4de0c fixes a bunch of other JRuby issues, but I wasn't able to reproduce this one.

**Comment by graaff** [comment]
I'm still seeing this with sass 3.2.3.

**Comment by nex3** [comment]
I can't really do anything about this without being able to reproduce it myself. If you can find a fix, or figure out what I might need to do to reproduce it, I'll look into it.
