### ISSUE TITLE
Document the :sourcemap engine option

### ISSUE THREAD

**Issue by nex3** [sass/sass#584]
`Sass::Plugin::Compiler` now supports a `:sourcemap` option, which should be documented in the reference.

**Comment by nex3** [comment]
This should also be documented in the changelog.

**Comment by Snugug** [comment]
Along the same lines of this, how can one activate sourcemap from the command line? I've tried `sass --watch sass:css --sourcemap` and get the following error:

``` bash
sass --watch sass:css --sourcemap --trace
>>> Sass is watching for changes. Press Ctrl-C to stop.
/usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/plugin/compiler.rb:174:in `update_stylesheets': uninitialized constant Sass::Plugin::Compiler::Util (NameError)
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/plugin/compiler.rb:170:in `each'
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/plugin/compiler.rb:170:in `update_stylesheets'
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/plugin/compiler.rb:169:in `each'
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/plugin/compiler.rb:169:in `update_stylesheets'
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/plugin/compiler.rb:214:in `watch'
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/plugin.rb:107:in `send'
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/plugin.rb:107:in `method_missing'
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/exec.rb:475:in `watch_or_update'
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/exec.rb:317:in `process_result'
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/exec.rb:41:in `parse'
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/../lib/sass/../sass/exec.rb:21:in `parse!'
    from /usr/local/gems/sass-3.3.0.alpha.93/bin/sass:8
    from /usr/local/bin/sass:19:in `load'
    from /usr/local/bin/sass:19
```
