### ISSUE TITLE
SASS stopped compiling -- Urgent

### ISSUE THREAD

**Issue by ricardozea** [sass/sass#590]
Note that I'm not a programmer.

Until yesterday SASS was working just fine, now, SASS doesn't compile my `.scss` file anymore.

Here's what I've tried so far but nothing fixes the problem:
1. Uninstalling current version of SASS and installing an older version
2. Reinstalling the latest version of SASS
3. Uninstalling Ruby and installing the latest version
4. Installing the Listen gem
5. Adding a temporary CSS rule in my `.scss` file (doing this seemed to have partially worked for someone, see link to StackOverflow post at the bottom)
6. Rebooting my machine
7. Did everyone else's solutions here but none worked for me

**Technical information:**
- Win7 x64
- SASS version 3.2.3
- Compass version 0.12.2
- CMD commands used: `sass --watch scss:css --style compact --compass --debug-info`
- Editor: Sublime Text 2

**Other information:**

Something weird that happens is that if I write something incorrect in my `.scss` file, for example a four digit hex value for a color like `#f00a` and then run `--watch`, SASS immediately detects the problem, and rewrites the `.css` file with the error.

This means that SASS is, in some way, partially working.

After typing all the `--watch` commands, SASS initiates normally saying: `>>> Sass is watching for changes. Press Ctrl-C to stop.`

So, when I save my `.scss` file, SASS doesn't compile anymore. It just stays there.

Thing is that now I can't work on my projects anymore since there's no way to create CSS files anymore, so any help on this is immensely appreciated.

Thanks.

**--UPDATE**

I'm still not able to compile.

However, after stopping the `--watch` I get a huge list of items in my CMD. In my home PC SASS is working fine and when I stop watching I don't get any list like this one or anything:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

c:\[project folder path]\www>sass --watch scss:css --style compact --compass --debug-info --trace
>>> Sass is watching for changes. Press Ctrl-C to stop.

C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/util/multibyte_string_sc anner.rb:36:in `scan': Interrupt from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/util/multibyte_string_scanner.rb:36:in `scan'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:1142:in `tok'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:865:in `value!'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:845:in `declaration'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:568:in `block in declaration_or_ruleset'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:1090:in `block in catch_error'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:1090:in `catch'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:1090:in `catch_error'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:567:in `declaration_or_ruleset'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:540:in `block_child'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:532:in `block_contents'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:521:in `block'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:515:in `ruleset'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:539:in `block_child'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:532:in `block_contents'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:70:in `stylesheet'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/scss/parser.rb:27:in `parse'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/engine.rb:342:in `_to_tree'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/engine.rb:315:in `_render'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/engine.rb:262:in `render'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/plugin/compiler.rb:341:in `update_stylesheet'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/plugin/compiler.rb:203:in `block in update_stylesheets'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/plugin/compiler.rb:201:in `each'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/plugin/compiler.rb:201:in `update_stylesheets'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/plugin/compiler.rb:235:in `watch'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/plugin.rb:107:in `method_missing'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/exec.rb:444:in `watch_or_update'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/exec.rb:307:in `process_result'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/exec.rb:41:in `parse'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/exec.rb:21:in `parse!'
    from C:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/bin/sass:8:in `<top(required)>'
    from C:/Ruby193/bin/sass:23:in `load'
    from C:/Ruby193/bin/sass:23:in `<main>'
Terminate batch job (Y/N)?
```

Is there something wrong with the CSS parser or something?
## 

I created a post in StackOverflow as well: http://stackoverflow.com/questions/13766178/sass-scss-file-not-compiling-anymore

**Comment by ricardozea** [comment]
Similar issue being discussed here: https://github.com/nex3/sass/issues/362
