### ISSUE TITLE
@import 'file' on windows fails with more than 1 subdir in the path

### ISSUE THREAD

**Issue by dlmiles** [sass/sass#594]
ruby sass (3.2.3)   on window using RubyInstaller runtime

Project directory:  F:\Devel\foobar\project

I have a file:

\stylesheets\project.scss with the following 1 line:

``` css
    @import  "reset";
```

\stylesheets\_reset.scss with the following 1 line:

``` css
    body { }
```

It appear to matter which working directory 'sass' is run from and which path is provided to the Ruby program.

WORKS: cd F:\Devel\foobar\project\stylesheets; sass project.scss
WORKS: cd F:\Devel\foobar\project; sass stylesheets\project.scss
FAILS: cd F:\Devel\foobar; sass project\stylesheets\project.scss
FAILS: sass F:\Devel\foobar\project\stylesheets\project.scss

The failure is reported as:
   _Syntax error: File to import not found or unreadable: reset_

**Comment by nex3** [comment]
I can't reproduce this on Linux. Can you provide the full output when you run Sass with `--trace`?

Does this happen on other Windows machines? Is there anything unusual about your filesystem? About the "project" directory?

**Comment by dlmiles** [comment]
What things can I say about setup.   RubyInstaller is installed to F:\Ruby193 (not C:) as this is SSD disk at F:

The 3rd case was being tested, which is the top FAILS where I am one directory up from the standard layout with "stylesheets" and other such directories.

My main use case is the absolute path, i.e. I would like:

```
FAILS: sass F:\Devel\foobar\project\stylesheets\project.scss
```

to work.  But I found when testing to write bug report I only needed to be one level up and still using a relative path to make it fail.

A file exists F:\Devel\ChangedDirName1\changed.dir.name2\foo\bar\ruby\config.rb  but I presume it has no effect on anything, if I rename it "config.rbxyz" the 2nd case continues to WORKS.

``` text
F:\Devel\ChangedDirName1\changed.dir.name2\foo\bar>sass --trace ruby\stylesheets\project.scss
ruby\stylesheets\project.scss:2: File to import not found or unreadable: reset. (Sass::SyntaxError)
Load path: F:/Devel/ChangedDirName1/changed.dir.name2/foo/bar
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/import_node.rb:67:in `rescue in import'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/import_node.rb:45:in `import'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/import_node.rb:28:in `imported_file'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/import_node.rb:37:in `css_import?'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/perform.rb:215:in `visit_import'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/base.rb:37:in `visit'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/perform.rb:98:in `visit'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/base.rb:53:in `map'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/base.rb:53:in `visit_children'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/perform.rb:107:in `block in visit_children'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/perform.rb:119:in `with_environment'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/perform.rb:106:in `visit_children'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/base.rb:37:in `block in visit'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/perform.rb:126:in `visit_root'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/base.rb:37:in `visit'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/perform.rb:98:in `visit'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/visitors/perform.rb:7:in `visit'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/tree/root_node.rb:20:in `render'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/engine.rb:315:in `_render'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/engine.rb:262:in `render'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/exec.rb:329:in `process_result'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/exec.rb:41:in `parse'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/lib/sass/exec.rb:21:in `parse!'
        from F:/Ruby193/lib/ruby/gems/1.9.1/gems/sass-3.2.3/bin/sass:8:in `<top (required)>'
        from F:/Ruby193/bin/sass:23:in `load'
        from F:/Ruby193/bin/sass:23:in `<main>'
```

**Comment by dlmiles** [comment]
I have tested on linux as well and indeed all 4 use cases do work in their equivalent forms.

**Comment by dlmiles** [comment]
Have debugged on windows and provided a code fix for this in https://github.com/nex3/sass/pull/619
