### ISSUE TITLE
undefined method `add_template_location' for Sass::Plugin:Module

### ISSUE THREAD

**Issue by mrbrdo** [sass/sass#67]
I upgraded rails for a site of mine. It said I need to install the sass gem so I did. But now, when I run rails:update, I get:

```
$ rake rails:update --trace
(in /home/mrbrdo/rails/profesorji)
rake aborted!
undefined method `add_template_location' for Sass::Plugin:Module
/home/mrbrdo/rails/profesorji/config/application.rb:41
/home/mrbrdo/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
/home/mrbrdo/.rvm/rubies/ruby-1.8.7-p334/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'
/home/mrbrdo/rails/profesorji/Rakefile:4
/home/mrbrdo/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2383:in `load'
/home/mrbrdo/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2383:in `raw_load_rakefile'
/home/mrbrdo/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2017:in `load_rakefile'
/home/mrbrdo/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/mrbrdo/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2016:in `load_rakefile'
/home/mrbrdo/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2000:in `run'
/home/mrbrdo/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/home/mrbrdo/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/home/mrbrdo/.rvm/gems/ruby-1.8.7-p334/gems/rake-0.8.7/bin/rake:31
/home/mrbrdo/.rvm/gems/ruby-1.8.7-p334/bin/rake:19:in `load'
/home/mrbrdo/.rvm/gems/ruby-1.8.7-p334/bin/rake:19
```

**Comment by mrbrdo** [comment]
I'm sorry, I just saw the error is actually coming from my application.rb config file. What should I use now, instead of that?
Sass::Plugin.add_template_location('public/stylesheets/sass', 'public/stylesheets')

Thanks.

**Comment by chriseppstein** [comment]
That still works -- I use it in compass. Do you still have haml 3.0 installed?

**Comment by mrbrdo** [comment]
Using haml (3.1.0)
Using haml-rails (0.3.4)
