### ISSUE TITLE
v3.2.6 appears to be broken, whereas v3.2.3 is fine?

### ISSUE THREAD

**Issue by lukearmstrong** [sass/sass#677]
I have tried this on three servers, one running CentOS and two running RHEL. Here is what is installed.

```
ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-linux]

*** LOCAL GEMS ***

bigdecimal (1.1.0)
bundler (1.3.1, 1.2.1)
chunky_png (1.2.7, 1.2.6)
compass (0.12.2)
ffi (1.4.0, 1.1.5)
fssm (0.2.10, 0.2.9)
io-console (0.4.2, 0.3)
json (1.7.7, 1.5.4)
listen (0.7.3, 0.5.3)
minitest (4.6.2, 2.5.1)
rake (10.0.3, 0.9.2.2)
rb-inotify (0.9.0, 0.8.8)
rdoc (4.0.0, 3.9.4)
sass (3.2.3, 3.2.6)
```

I installed Ruby and Sass on the servers at different times, so I ended up with v3.2.3 on two of our servers, and v3.2.6 on our other server. Sass v3.2.6 just hangs, here is the output of a `--trace`.

```
/usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:1156:in `scan': Interrupt
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:1156:in `tok'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:879:in `value!'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:859:in `declaration'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:582:in `block in declaration_or_ruleset'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:1104:in `block in catch_error'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:1104:in `catch'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:1104:in `catch_error'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:581:in `declaration_or_ruleset'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:554:in `block_child'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:543:in `block_contents'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:535:in `block'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:529:in `ruleset'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:591:in `block in declaration_or_ruleset'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:1104:in `block in catch_error'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:1104:in `catch'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:1104:in `catch_error'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:591:in `declaration_or_ruleset'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:554:in `block_child'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:546:in `block_contents'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:535:in `block'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:349:in `media_directive'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:175:in `special_directive'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:147:in `directive'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:553:in `block_child'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:546:in `block_contents'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:82:in `stylesheet'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/scss/parser.rb:27:in `parse'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/engine.rb:342:in `_to_tree'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/engine.rb:274:in `to_tree'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/perform.rb:225:in `visit_import'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/base.rb:37:in `visit'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/perform.rb:100:in `visit'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/base.rb:53:in `map'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/base.rb:53:in `visit_children'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/base.rb:37:in `block in visit'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/base.rb:37:in `visit'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/perform.rb:100:in `visit'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/visitors/perform.rb:7:in `visit'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/tree/root_node.rb:20:in `render'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/engine.rb:315:in `_render'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/engine.rb:262:in `render'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/plugin/compiler.rb:341:in `update_stylesheet'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/plugin/compiler.rb:203:in `block in update_stylesheets'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/plugin/compiler.rb:201:in `each'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/plugin/compiler.rb:201:in `update_stylesheets'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/plugin.rb:81:in `update_stylesheets'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/exec.rb:424:in `watch_or_update'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/exec.rb:307:in `process_result'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/exec.rb:41:in `parse'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/lib/sass/exec.rb:21:in `parse!'
        from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.2.6/bin/sass:9:in `<top (required)>'
        from /usr/local/bin/sass:23:in `load'
        from /usr/local/bin/sass:23:in `<main>'
```

If I can provide any more information to help diagnose this issue then let me know.

**Comment by nex3** [comment]
What command are you running when it hangs? What Sass file are you running it against? Can you remove styles from that file and still cause it to hang?

**Comment by lukearmstrong** [comment]
This is the command:
`sass --update --force public/assets/sass/main.scss:public/assets/css/main.css`

Here are the files:
https://gist.github.com/lukearmstrong/158c073e8b427d7c3e8c

**Comment by lukearmstrong** [comment]
Thank you for fixing this @nex3

**Comment by nex3** [comment]
Thanks for reporting it!
