### ISSUE TITLE
Interpolating variable within multi-line comment

### ISSUE THREAD

**Issue by emilbayes** [sass/sass#732]
The following snippet throws an error that `$Hf` is undefined (because it's commented out), even though the whole statement is commented out. I do not know if this is expected behaviour, but I wouldn't think so.

```
/*figure {
    $Hf: 0.85;
    font-size: #{$Hf}em;
    margin: 0 #{(0.75/$Hf)}em #{(1.5/$Hf)}em #{(0.75/$Hf)}em;
}
*/
```

The full backtrace:

```
$ sass resources/source/sass/test.scss  --trace
resources/source/sass/test.scss:1: Undefined variable: "$Hf". (Sass::SyntaxError)
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/script/variable.rb:49:in `_perform'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/script/node.rb:50:in `perform'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/perform.rb:410:in `block in run_interp_no_strip'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/perform.rb:408:in `map'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/perform.rb:408:in `run_interp_no_strip'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/perform.rb:137:in `visit_comment'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/base.rb:37:in `visit'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/perform.rb:100:in `visit'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/base.rb:53:in `map'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/base.rb:53:in `visit_children'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/base.rb:37:in `block in visit'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/base.rb:37:in `visit'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/perform.rb:100:in `visit'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/visitors/perform.rb:7:in `visit'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/root_node.rb:36:in `css_tree'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/tree/root_node.rb:20:in `render'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/engine.rb:265:in `render'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/exec.rb:358:in `process_result'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/exec.rb:41:in `parse'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/lib/sass/exec.rb:21:in `parse!'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/gems/sass-3.3.0.alpha.134/bin/sass:9:in `<top (required)>'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/bin/sass:23:in `load'
    from /Users/melgaard/.rvm/gems/ruby-1.9.3-preview1/bin/sass:23:in `<main>'
```

**Comment by nex3** [comment]
Block comments are emitted to CSS; as such, they resolve interpolation so you can include dynamic content (see haml/haml#60). You can avoid this by putting a backslash before the interpolation, or by using silent single-line comments.
