### ISSUE TITLE
3.1.1: NameError if FileUtils has not been required

### ISSUE THREAD

**Issue by TheAdmiral** [sass/sass#80]
Hi there,

I'm using SASS 3.1.1 as a library through plain ol' Ruby 1.9.2 (not through Rails). If FileUtils has not been required prior to running to_css on a SASS Engine object, I get the following NameError:

```
/usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/cache_stores/filesystem.rb:37:in `_store': uninitialized constant Sass::CacheStores::Filesystem::FileUtils (NameError)
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/cache_stores/base.rb:51:in `store'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/cache_stores/chain.rb:19:in `block in store'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/cache_stores/chain.rb:19:in `each'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/cache_stores/chain.rb:19:in `store'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/engine.rb:330:in `_to_tree'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/engine.rb:250:in `to_tree'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/perform.rb:144:in `visit_import'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/base.rb:37:in `visit'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/perform.rb:18:in `visit'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/base.rb:53:in `map'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/base.rb:53:in `visit_children'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/perform.rb:27:in `block in visit_children'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/perform.rb:39:in `with_environment'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/perform.rb:26:in `visit_children'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/base.rb:37:in `block in visit'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/perform.rb:47:in `visit_root'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/base.rb:37:in `visit'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/perform.rb:18:in `visit'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/visitors/perform.rb:7:in `visit'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/tree/root_node.rb:20:in `render'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/engine.rb:291:in `_render'
    from /usr/local/lib/ruby/gems/1.9.1/gems/sass-3.1.1/lib/sass/engine.rb:238:in `render'
```

**Comment by dbrock** [comment]
I ran into this too.
