### ISSUE TITLE
Install prerelease gem of sass 3.3 failed (sass requires listen (~> 0.7))

### ISSUE THREAD

**Issue by suamikim** [sass/sass#811]
I'm trying to install the prerelease version of sass (3.3) because of the added sourcemap support but it fails with the following error:

```
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: sass requires listen (~> 0.7)
```

I used the following command:

```
gem install sass --pre
```

Until now i had sass v3.2.8 installed. Uninstalling this one prior installing the pre-version did not help.

Any ideas?

One more thing: I also thought about installing it directly from the git-repository but i don't know from which branch i can get the pre-version?

I've posted this question also on stackoverflow: http://stackoverflow.com/questions/17231778/install-prerelease-gem-of-sass-3-3-failed-sass-requires-listen-0-7
## 

Edit:
I just tried to install the master-branch from git-hub with "rake install", but this gives me the following error:

```
WARNING: vendor/listen doesn't exist, and this isn't a git repository so I can't get it automatically!
chmod -R a+rx bin
rake aborted!
Command failed with status (127): [chmod -R a+rx bin...]
C:/Users/xxx/sass-master/Rakefile:44:in `block in <top (required)>'
Tasks: TOP => install => package => permissions
(See full trace by running task with --trace)
```

**Comment by suamikim** [comment]
As stated in the thread on stackoverflow (http://stackoverflow.com/a/17237829/1273551) it's necessary to install a specific version instead of giving the --pre option.

For me the following statement was working:

```
gem install sass --version=3.3.0.alpha.184
```

Therefore this can be closed...

**Comment by polikin** [comment]
When I try to compile.. I have few errors.. What I'm suppose to do with this?

```
    from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:118:in `rescue in require'
    from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:124:in `require'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches/browser_support.rb:1:in `<top (required)>'
    from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:2:in `block in <top (required)>'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `each'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions/monkey_patches.rb:1:in `<top (required)>'
    from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass/sass_extensions.rb:9:in `<top (required)>'
    from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:5:in `block in <top (required)>'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `each'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/lib/compass.rb:4:in `<top (required)>'
    from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/bin/compass:20:in `block in <top (required)>'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/bin/compass:8:in `fallback_load_path'
    from C:/Ruby200/lib/ruby/gems/2.0.0/gems/compass-0.12.2/bin/compass:19:in `<top (required)>'
    from C:/Program Files (x86)/Prepros/bin/gems.rb:17:in `load'
    from C:/Program Files (x86)/Prepros/bin/gems.rb:17:in `<main>'


C:/Ruby200/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:118:in `require': cannot load such file -- sass/script/node (LoadError)
```

**Comment by nex3** [comment]
@polikin It looks like maybe you don't have Sass installed. I'm not sure how that would have happened, but try running `gem install sass` and see if that works.

For future reference, [the mailing list](https://groups.google.com/forum/#!forum/sass-lang) is a better place to ask support questions.

**Comment by polikin** [comment]
I have Sass 3.2.13 (Media Mark). When I try with 3.3 .. I see those 
errors when I try to compile.

##

**Comment by nex3** [comment]
Sass 3.3 doesn't have the same file structure as 3.2. Compass 0.12 is only compatible with 3.2, not 3.3.

**Comment by polikin** [comment]
So I need to update Compass.
