### ISSUE TITLE
Cannot use sprite with sass --compass

### ISSUE THREAD

**Issue by MoOx** [sass/sass#89]
I'm trying to use sprite mixins  but I'm using sass --compass (since
I'm waiting for compass to have an import path command line option)
When I use sass --compass for a code which work with normal compass bin, i've this error:
NoMethodError: undefined method `top' for nil:NilClass

Chris tell me it's is normal. So here is the stacktrace:

```
/Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/sass_extensions/
sprites/base.rb:54:in `compute_image_metadata!': undefined method
`top' for nil:NilClass (NoMethodError)
       from /Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/
sass_extensions/sprites/base.rb:39:in `initialize'
       from /Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/
sass_extensions/sprites/base.rb:15:in `new'
       from /Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/
sass_extensions/sprites/base.rb:15:in `from_uri'
       from /Library/Ruby/Gems/1.8/gems/compass-0.11.1/lib/compass/
sass_extensions/functions/sprites.rb:24:in `sprite_map'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
script/funcall.rb:80:in `send'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
script/funcall.rb:80:in `_perform'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
script/node.rb:40:in `perform'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:236:in `visit_variable'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:37:in `send'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:37:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:18:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:53:in `visit_children'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:53:in `map'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:53:in `visit_children'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:27:in `visit_children'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:39:in `with_environment'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:26:in `visit_children'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:37:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:47:in `visit_root'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:37:in `send'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/base.rb:37:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:18:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:7:in `send'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/visitors/perform.rb:7:in `visit'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
tree/root_node.rb:20:in `render'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
engine.rb:291:in `_render'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
engine.rb:238:in `render'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
exec.rb:316:in `process_result'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
exec.rb:41:in `parse'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/../lib/sass/../sass/
exec.rb:21:in `parse!'
       from /Library/Ruby/Gems/1.8/gems/sass-3.1.1/bin/sass:8
       from /usr/bin/sass:19:in `load'
       from /usr/bin/sass:19
```

**Comment by nex3** [comment]
This should probably be on the Compass issue tracker, since the error appears to be in a Compass-defined function.

**Comment by MoOx** [comment]
Yep your right. Sorry :)

**Comment by chriseppstein** [comment]
Well it works in Compass but not in Sass. So let's track it here, but maybe the fix will end up being in the compass code... Assigning to me.

**Comment by MoOx** [comment]
Ok, after some work on this, I found it's not definitely not a sass related problem. I've reproduce this but with just compass.

http://groups.google.com/group/compass-users/browse_thread/thread/8e655d6706ca6d2d

So, maybe I will open an issue in Compass.
