### ISSUE TITLE
Sporadic ENOENT while rendering inline scss

### ISSUE THREAD

**Issue by jdelStrother** [sass/sass#925]
There's a couple of points in our codebase where we render scss inline in a haml template.  Every so often on our live site, I get an error along the lines of : 

```
Errno::ENOENT: No such file or directory - /app/audioboo/code/tmp/cache/sass/23a327688ce0eb5b160ef19a41442685a20434c3/(__TEMPLATE__)c


[GEM_ROOT]/gems/sass-3.2.7/lib/sass/cache_stores/filesystem.rb:25:in `unlink'
[GEM_ROOT]/gems/sass-3.2.7/lib/sass/cache_stores/filesystem.rb:25:in `_retrieve'
[GEM_ROOT]/gems/sass-3.2.7/lib/sass/cache_stores/base.rb:62:in `retrieve'
[GEM_ROOT]/gems/sass-3.2.7/lib/sass/cache_stores/chain.rb:25:in `block in retrieve'
[GEM_ROOT]/gems/sass-3.2.7/lib/sass/cache_stores/chain.rb:24:in `each'
[GEM_ROOT]/gems/sass-3.2.7/lib/sass/cache_stores/chain.rb:24:in `each_with_index'
[GEM_ROOT]/gems/sass-3.2.7/lib/sass/cache_stores/chain.rb:24:in `retrieve'
[GEM_ROOT]/gems/sass-3.2.7/lib/sass/engine.rb:333:in `_to_tree'
[GEM_ROOT]/gems/sass-3.2.7/lib/sass/engine.rb:315:in `_render'
[GEM_ROOT]/gems/sass-3.2.7/lib/sass/engine.rb:262:in `render'
[GEM_ROOT]/gems/sass-rails-3.2.6/lib/sass/rails/template_handlers.rb:106:in `evaluate'
[GEM_ROOT]/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/sass_rails_filter.rb:8:in `render'
(eval):5:in `render_with_options'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/filters.rb:184:in `block in compile'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/filters.rb:162:in `instance_eval'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/filters.rb:162:in `compile'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/filters.rb:141:in `internal_compile'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:267:in `compile_filter'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:18:in `compile'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:20:in `block (2 levels) in compile'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:20:in `each'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:20:in `block in compile'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:129:in `compile_silent_script'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:20:in `compile'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:20:in `block (2 levels) in compile'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:20:in `each'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:20:in `block in compile'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:93:in `compile_root'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/compiler.rb:20:in `compile'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/engine.rb:66:in `initialize'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/template/plugin.rb:25:in `new'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/template/plugin.rb:25:in `compile'
[GEM_ROOT]/bundler/gems/haml-9d7711bbc294/lib/haml/template/plugin.rb:30:in `call'
[GEM_ROOT]/bundler/gems/rails-a9d4fa337af4/actionpack/lib/action_view/template.rb:268:in `compile'
...
```

It seems to resolve itself on the next hit.  We don't use threads, but do have multiple unicorn processes, and I've wondered if it's due to two unicorns compiling the template at the same time, but never been able to pin it down.  Has anyone else run into anything similar?

**Comment by nex3** [comment]
@chriseppstein has done a substantial amount of work recently to make Sass more threadsafe and to make the cache accesses atomic. This should fix this issue. Feel free to re-open if it doesn't.
