### ISSUE TITLE
sass compile error - StalenessChecker::Mutex (NameError)

### ISSUE THREAD

**Issue by kuldeeparora** [sass/sass#947]
the sass compile fails - 3.2.11

```
[Assetic\Exception\FilterException]                                                                                
An error occurred while running:                                                                                   
'/opt/vagrant_ruby/bin/ruby' '/usr/local/bin/compass' 'compile' '/tmp' '--images-dir'     '/projects/repos/tva/app/..  
/src/App/PlayerBundle/Resources/public/assets/img' '--config'    '/tmp/assetic_compassS4tJ7l' '--sass-dir' '' '--css  
 -dir' '' '/tmp/assetic_compasstopJ7I.scss'                                                                         

  Error Output:                                                                                                      
   /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/sass-    3.2.11/lib/sass/../sass/plugin/staleness_checker.rb:27: uninitialized constant Sass::Plugin::StalenessChecker::Mutex (NameError)                                                      
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'             
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'                          
from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/sass-  3.2.11/lib/sass/../sass/plugin/compiler.rb:7                   
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'             
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'                          
from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/sass-3.2.11/lib/sass/../sass/plugin.rb:4                            
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'             
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'                          
from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/compass-0.12.2/lib/compass/commands/watch_project.rb:5              
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'             
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'                          
from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/compass-0.12.2/lib/compass/commands.rb:11                           
from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/compass-0.12.2/lib/compass/commands.rb:6:in `each'                  
from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/compass-0.12.2/lib/compass/commands.rb:6                            
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'             
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'                          
from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/compass-0.12.2/lib/compass/exec.rb:7                                
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'             
from /opt/vagrant_ruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36:in `require'                          
from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/compass-0.12.2/bin/compass:21                                       
from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/compass-0.12.2/bin/compass:8:in `fallback_load_path'                
from /opt/vagrant_ruby/lib/ruby/gems/1.8/gems/compass-0.12.2/bin/compass:19                                       
from /usr/local/bin/compass:19:in `load'                                                                          
from /usr/local/bin/compass:19                                                                                    
```

**Comment by nex3** [comment]
Duplicate of #941.
